#USAGE: Input parameters: $1=year $2=selection $3region

#Here variables from specific selections
if [ "$2" == "GGFcateg1_SR_110" ]; then
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                     --log --no-data --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1  --ymax 1e6 --quit --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var GGFMVA1                --sel Btag4_$2_$3 --no-sr-namecompl --title ";GGFMVA1 ;Events"                       --log --blind-range 0.7 1    --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-2 --ymax 1e6 --ratio --quit --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var BDT3cat1               --sel Btag4_$2_$3 --no-sr-namecompl --title ";TMVAcat1 ;Events"                       --log --blind-range 0.7 1    --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-2 --ymax 1e6 --ratio --quit --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (3rd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (2nd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bres        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Res-score (2nd b-tagged jet);Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H_{1}) |;Events"          --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
elif [ "$2" == "GGFcateg2_SR_110" ]; then
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                     --log --no-data --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1  --ymax 1e6 --quit --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var GGFMVA2                --sel Btag4_$2_$3 --no-sr-namecompl --title ";GGFMVA2 ;Events"                       --log --blind-range 0.7 1    --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-2 --ymax 1e6 --ratio --quit --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var BDT3cat2               --sel Btag4_$2_$3 --no-sr-namecompl --title ";TMVAcat2 ;Events"                       --log --blind-range 0.7 1    --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-2 --ymax 1e6 --ratio --quit --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (3rd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (2nd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bres        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Res-score (2nd b-tagged jet);Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H_{1}) |;Events"          --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
elif [ "$2" == "GGFcateg1_CR_210" ] || [ "$2" == "GGFcateg1_CR_110" ] || [ "$2" == "GGFcateg1_SR_210" ] ; then
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var GGFMVA1                --sel Btag4_$2_$3 --no-sr-namecompl --title "; GGFMVA1 ;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (3rd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b2_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (2nd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bres        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Res-score (3rd b-tagged jet);Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H_{1}) |;Events"          --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
elif [ "$2" == "GGFcateg2_CR_210" ] || [ "$2" == "GGFcateg2_CR_110" ] || [ "$2" == "GGFcateg2_SR_210" ] ; then
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var GGFMVA2                --sel Btag4_$2_$3 --no-sr-namecompl --title "; GGFMVA2 ;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_m_rot               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (3rd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b2_bscore      --sel Btag4_$2_$3 --no-sr-namecompl --title ";Deepjet (2nd b-tagged jet);Events"    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_btag_b3_bres        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Res-score (3rd b-tagged jet);Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H_{1}) |;Events"          --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
elif [ "$2" == "VBFcateg1_SR_110" ]; then
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount   --sel  Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"      --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e6 --quit --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m_1       --sel  Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"     --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e4 --quit --DataCond $1 --sigscale 1     
elif [ "$2" == "VBFcateg2_SR_110" ]; then
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount   --sel  Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"      --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e6 --quit --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m_2       --sel  Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"     --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e4 --quit --DataCond $1 --sigscale 1     
elif [ "$2" == "VBFcateg1_SR_210" ] || [ "$2" == "VBFcateg2_SR_210" ] || [ "$2" == "VBFcateg1_CR_110" ] || [ "$2" == "VBFcateg2_CR_110" ] || [ "$2" == "VBFcateg1_CR_210" ] || [ "$2" == "VBFcateg2_CR_210" ]; then
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m_1             --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var HH_m_2             --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_m_rot           --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_m_rot           --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2)' [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var JJ_m               --sel Btag4_$2_$3 --no-sr-namecompl --title ";JJ invariant mass [GeV];Events"       --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var j1j2_deltaEta      --sel Btag4_$2_$3 --no-sr-namecompl --title ";#Delta#eta(JJ);Events"                --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H1_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var H2_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var h1h2_deltaEta      --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var h1h2_deltaPhi      --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#phi(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyBkgModelHistosWithBDT/Histos$1 --var EventCount         --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
else
   echo "Selection is not defined"
fi