#USAGE: Input parameters: $1=year $2=selection $3region

#Here variables from specific selections
if [ "$2" == "GGFcateg1_SR_110" ]; then
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                              --log --no-data --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1  --ymax 1e6 --quit --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var GGFMVA1                --sel Btag4_$2_$3 --no-sr-namecompl --title ";GGFMVA1 ;Events"                                --log --blind-range 0.7 1    --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-2 --ymax 1e6 --ratio --quit --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b1_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b1_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b2_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b2_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"                      --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"                      --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_1                 --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"                       --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"                       --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H_{1}) |;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_b1_h1cm   --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(b)| in H1-frame;Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(HH) [GeV];Events"                         --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_4b_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 4 b's regressed P_{T};Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_3b_bres            --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 3 b's resolution score;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var min_4b_deltaR          --sel Btag4_$2_$3 --no-sr-namecompl --title ";Min|#DeltaR(bb)|;Events"                        --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var max_4b_deltaEta        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Max|#Delta#eta(bb)|;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var nBtagTightonMediumWP   --sel Btag4_$2_$3 --no-sr-namecompl --title ";N. of tight b-tags in 3 most b-tagged;Events"   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
elif [ "$2" == "GGFcateg2_SR_110" ]; then
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                              --log --no-data --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1  --ymax 1e6 --quit --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var GGFMVA2                --sel Btag4_$2_$3 --no-sr-namecompl --title ";GGFMVA2 ;Events"                                --log --blind-range 0.7 1    --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-2 --ymax 1e6 --ratio --quit --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b1_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b1_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b2_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b2_ptRegressed      --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"                      --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"                      --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_1                 --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"                       --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"                       --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H_{1}) |;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_b1_h1cm   --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(b)| in H1-frame;Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(HH) [GeV];Events"                         --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_4b_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 4 b's regressed P_{T};Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_3b_bres            --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 3 b's resolution score;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var min_4b_deltaR          --sel Btag4_$2_$3 --no-sr-namecompl --title ";Min|#DeltaR(bb)|;Events"                        --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var max_4b_deltaEta        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Max|#Delta#eta(bb)|;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var nBtagTightonMediumWP   --sel Btag4_$2_$3 --no-sr-namecompl --title ";N. of tight b-tags in 3 most b-tagged;Events"   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
elif [ "$2" == "GGFcateg1_CR_210" ] || [ "$2" == "GGFcateg1_CR_110" ] || [ "$2" == "GGFcateg1_SR_210" ] ; then
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var GGFMVA1                --sel Btag4_$2_$3 --no-sr-namecompl --title "; GGFMVA1 ;Events"                           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_1                 --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H_{1}) |;Events"          --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_b1_h1cm   --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(b)| in H1-frame;Events"   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(HH) [GeV];Events"               --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_4b_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 4 b's regressed P_{T};Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_3b_bres            --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 3 b's resolution score;Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var min_4b_deltaR          --sel Btag4_$2_$3 --no-sr-namecompl --title ";Min|#DeltaR(bb)|;Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var max_4b_deltaEta        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Max|#Delta#eta(bb)|;Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var nBtagTightonMediumWP   --sel Btag4_$2_$3 --no-sr-namecompl --title ";N. of tight b-tags in 3 most b-tagged;Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
elif [ "$2" == "GGFcateg2_CR_210" ] || [ "$2" == "GGFcateg2_CR_110" ] || [ "$2" == "GGFcateg2_SR_210" ] ; then
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var GGFMVA2                --sel Btag4_$2_$3 --no-sr-namecompl --title "; GGFMVA2 ;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1) [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2) [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m                   --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_1                 --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var h1h2_deltaEta          --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{1} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_bb_deltaR           --sel Btag4_$2_$3 --no-sr-namecompl --title ";H_{2} #DeltaR(bb);Events"             --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_ggfcm     --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(H)| in HH-frame;Events"   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var abs_costh_H1_b1_h1cm   --sel Btag4_$2_$3 --no-sr-namecompl --title ";|cos#theta*(b)| in H1-frame;Events"   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_pt                  --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(HH) [GeV];Events"               --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_4b_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 4 b's regressed P_{T};Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var sum_3b_bres            --sel Btag4_$2_$3 --no-sr-namecompl --title ";Sum of 3 b's resolution score;Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var EventCount             --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var min_4b_deltaR          --sel Btag4_$2_$3 --no-sr-namecompl --title ";Min|#DeltaR(bb)|;Events"              --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var max_4b_deltaEta        --sel Btag4_$2_$3 --no-sr-namecompl --title ";Max|#Delta#eta(bb)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var nBtagTightonMediumWP   --sel Btag4_$2_$3 --no-sr-namecompl --title ";N. of tight b-tags in 3 most b-tagged;Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
elif [ "$2" == "VBFcateg1_SR_110" ]; then
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var EventCount   --sel  Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"      --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e6 --quit --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_1       --sel  Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"     --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e4 --quit --DataCond $1 --sigscale 1     
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var GGFKiller          --sel Btag4_$2_$3 --no-sr-namecompl --title ";GGFKiller;Events"                     --log --blind-range 0.65 1.0  --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      
elif [ "$2" == "VBFcateg2_SR_110" ]; then
#   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var EventCount   --sel  Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"      --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e6 --quit --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_2       --sel  Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"     --log --no-data        --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e4 --quit --DataCond $1 --sigscale 1     
elif [ "$2" == "VBFcateg1_SR_210" ] || [ "$2" == "VBFcateg2_SR_210" ] || [ "$2" == "VBFcateg1_CR_110" ] || [ "$2" == "VBFcateg2_CR_110" ] || [ "$2" == "VBFcateg1_CR_210" ] || [ "$2" == "VBFcateg2_CR_210" ]; then
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b1_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 leading b-jet regressed P_{T} [GeV];Events"  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H1 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_b2_ptRegressed  --sel Btag4_$2_$3 --no-sr-namecompl --title ";H2 trailing b-jet regressed P_{T} [GeV];Events" --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_1             --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var HH_m_2             --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(HH) [GeV];Events"                   --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_m               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H1) [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_m               --sel Btag4_$2_$3 --no-sr-namecompl --title ";M(H2) [GeV];Events"                  --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var JJ_m               --sel Btag4_$2_$3 --no-sr-namecompl --title ";JJ invariant mass [GeV];Events"       --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1      
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var j1j2_deltaEta      --sel Btag4_$2_$3 --no-sr-namecompl --title ";#Delta#eta(JJ);Events"                --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H1_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{1}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var H2_pt              --sel Btag4_$2_$3 --no-sr-namecompl --title ";P_{T}(H_{2}) [GeV];Events"            --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var h1h2_deltaEta      --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#eta(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var h1h2_deltaPhi      --sel Btag4_$2_$3 --no-sr-namecompl --title ";|#Delta#phi(h1,h2)|;Events"           --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var EventCount         --sel Btag4_$2_$3 --no-sr-namecompl --title ";EventCount;Events"                    --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e7 --quit --ratio --DataCond $1 --sigscale 1 --tab
   python plotterDataDriven.py --dir ../MyLimitsHistos/Histos$1 --var GGFKiller          --sel Btag4_$2_$3 --no-sr-namecompl --title ";GGFKiller;Events"                     --log --leg-coords 0.38 0.60 0.85 0.93 --ymin 1e-1 --ymax 1e5 --quit --ratio --DataCond $1 --sigscale 1      

else
   echo "Selection is not defined"
fi