// Class: ReadBDT_200_300_2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_200_300_2
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/07       [396295]
Creator        : guerrero
Date           : Wed May 29 02:17:54 2019
Host           : Linux cmsbuild92.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/guerrero/Run2/HH2019/newcommit/CMSSW_10_2_5/src/bbbbAnalysis/mltraining/BackgroundRejection
Training events: 45930
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "300" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "5.000000e-02" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
HH_b3_pt                      HH_b3_pt                      HH_b3_pt                      HH_b3_pt                                                        'F'    [25.46875,711.5]
HH_b4_pt                      HH_b4_pt                      HH_b4_pt                      HH_b4_pt                                                        'F'    [25,457]
abs(HH_b3_eta)                HH_b3_eta                     HH_b3_eta                     HH_b3_eta                                                       'F'    [1.14422291517e-05,2.39990234375]
abs(HH_b4_eta)                HH_b4_eta                     HH_b4_eta                     HH_b4_eta                                                       'F'    [3.73274087906e-06,2.39990234375]
H1_m                          H1_m                          H1_m                          H1_m                                                            'F'    [15.9633493423,1901.06274414]
H2_m                          H2_m                          H2_m                          H2_m                                                            'F'    [16.2869777679,1880.68359375]
H1_bb_deltaR                  H1_bb_deltaR                  H1_bb_deltaR                  H1_bb_deltaR                                                    'F'    [0.390987694263,5.21348524094]
H2_bb_deltaR                  H2_bb_deltaR                  H2_bb_deltaR                  H2_bb_deltaR                                                    'F'    [0.400073736906,5.00242567062]
H1_bb_deltaPhi                H1_bb_deltaPhi                H1_bb_deltaPhi                H1_bb_deltaPhi                                                  'F'    [-3.14158368111,3.14158058167]
H2_bb_deltaPhi                H2_bb_deltaPhi                H2_bb_deltaPhi                H2_bb_deltaPhi                                                  'F'    [-3.14152264595,3.14135742188]
abs(costh_HH_b1_cm)           abs_costh_HH_b1_cm            abs_costh_HH_b1_cm            abs_costh_HH_b1_cm                                              'F'    [5.99807426624e-05,0.999978423119]
abs(costh_HH_b2_cm)           abs_costh_HH_b2_cm            abs_costh_HH_b2_cm            abs_costh_HH_b2_cm                                              'F'    [1.21999655676e-05,0.999894380569]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_200_300_2Node
   
#ifndef BDT_200_300_2Node__def
#define BDT_200_300_2Node__def
   
class BDT_200_300_2Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_200_300_2Node ( BDT_200_300_2Node* left,BDT_200_300_2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_200_300_2Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_200_300_2Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_200_300_2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_200_300_2Node*   fLeft;     // pointer to the left daughter node
   BDT_200_300_2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_200_300_2Node::~BDT_200_300_2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_200_300_2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_200_300_2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_200_300_2 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_200_300_2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_200_300_2" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HH_b3_pt", "HH_b4_pt", "abs(HH_b3_eta)", "abs(HH_b4_eta)", "H1_m", "H2_m", "H1_bb_deltaR", "H2_bb_deltaR", "H1_bb_deltaPhi", "H2_bb_deltaPhi", "abs(costh_HH_b1_cm)", "abs(costh_HH_b2_cm)" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_200_300_2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_200_300_2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_200_300_2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_200_300_2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_200_300_2Node*)current->GetRight();
         else current=(BDT_200_300_2Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT_200_300_2::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20367,-0.029633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766972,0.0266972) , 
4, 94.2252, 1, 0, 0.61154,0.11154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40225,-0.00977497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139206,-0.0360794) , 
4, 143.312, 1, 0, 0.235809,-0.264191) , 
6, 1.53957, 1, 0, 0.491425,-0.00857545)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196147,-0.0289332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714172,0.0204513) , 
4, 90.2935, 1, 0, 0.604611,0.100007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310482,-0.0182639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130514,-0.0351911) , 
4, 155.561, 1, 0, 0.202408,-0.283995) , 
6, 1.72489, 1, 0, 0.50284,0.00284144)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2028,-0.0270874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753353,0.0231031) , 
4, 92.1366, 1, 0, 0.619119,0.108488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4113,-0.00806731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154527,-0.0317522) , 
4, 137.188, 1, 0, 0.238312,-0.239393) , 
6, 1.54955, 1, 0, 0.499306,-0.000965581)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248235,-0.0221621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762037,0.0228419) , 
4, 96.7196, 1, 0, 0.62189,0.105241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396272,-0.00916416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154079,-0.0302799) , 
4, 137.781, 1, 0, 0.235305,-0.230177) , 
6, 1.55204, 1, 0, 0.499903,-0.000600664)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15202,-0.0298134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.018351) , 
4, 85.5315, 1, 0, 0.599513,0.0875274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184516,-0.0278123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470102,-0.00246035) , 
0, 117.286, 1, 0, 0.217,-0.245752) , 
4, 142.876, 1, 0, 0.506147,0.00617819)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224181,-0.0226937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700791,0.0160977) , 
4, 95.6335, 1, 0, 0.579873,0.0620885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0754815,-0.0369141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219901,-0.0225718) , 
5, 81.9114, 1, 0, 0.19267,-0.248346) , 
6, 1.84193, 1, 0, 0.489939,-0.0100148)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220187,-0.0270614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0628177,-0.0413251) , 
10, 0.637592, 1, 0, 0.14669,-0.330776) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709364,0.0190857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324583,-0.0158559) , 
7, 1.9929, 1, 0, 0.551896,0.0470926) , 
5, 68.4625, 1, 0, 0.503524,0.00198409)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267586,-0.0189787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730549,0.0184816) , 
4, 100.523, 1, 0, 0.58538,0.0666463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561244,0.00124431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169851,-0.0268975) , 
6, 1.21635, 1, 0, 0.208434,-0.234624) , 
4, 142.611, 1, 0, 0.489702,-0.00982307)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223221,-0.025275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674569,0.0157212) , 
5, 77.7493, 1, 0, 0.582266,0.0720397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190937,-0.0275308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438359,-0.00588945) , 
0, 106.865, 1, 0, 0.234933,-0.230686) , 
5, 142.683, 1, 0, 0.501322,0.00149133)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147099,-0.0269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733102,0.017614) , 
4, 82.9359, 1, 0, 0.628825,0.0954685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443622,-0.00538273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190699,-0.0232553) , 
4, 131.063, 1, 0, 0.270905,-0.169852) , 
6, 1.50668, 1, 0, 0.508476,0.00625638)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0814959,-0.0325416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203924,-0.0203007) , 
4, 74.6234, 1, 0, 0.116884,-0.276209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733221,0.016716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278281,-0.0164474) , 
6, 1.4722, 1, 0, 0.555983,0.0372741) , 
4, 83.7447, 1, 0, 0.491189,-0.00898424)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240723,-0.022531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707259,0.0173749) , 
5, 80.9666, 1, 0, 0.595608,0.0758836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414711,-0.00726552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194577,-0.0253332) , 
5, 134.152, 1, 0, 0.280955,-0.174938) , 
7, 2.24622, 1, 0, 0.501169,0.000602358)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213315,-0.0200523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716804,0.0152681) , 
4, 95.3893, 1, 0, 0.583827,0.0582421) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0841129,-0.0339663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237595,-0.0184052) , 
5, 83.4811, 1, 0, 0.204636,-0.205269) , 
4, 145.107, 1, 0, 0.495572,-0.00308905)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101796,-0.0283614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676641,0.0122342) , 
4, 75.6954, 1, 0, 0.597736,0.0658035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147432,-0.0259079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38451,-0.00797712) , 
0, 89.9012, 1, 0, 0.206731,-0.200948) , 
4, 142.611, 1, 0, 0.497281,-0.00272904)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171755,-0.0215421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699379,0.0129423) , 
4, 89.7562, 1, 0, 0.587361,0.05559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147248,-0.0247709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410206,-0.00534113) , 
0, 114.547, 1, 0, 0.180292,-0.206213) , 
4, 152.205, 1, 0, 0.504851,0.00252428)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2319,-0.0168802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731711,0.0150264) , 
4, 96.4568, 1, 0, 0.595348,0.0611129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275511,-0.0142028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140691,-0.0251164) , 
6, 2.2062, 1, 0, 0.190852,-0.194686) , 
6, 1.75591, 1, 0, 0.49344,-0.0033327)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270697,-0.0199703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747423,0.0196062) , 
5, 84.3114, 1, 0, 0.613629,0.0802791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430924,-0.00621987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230934,-0.0210335) , 
5, 130.616, 1, 0, 0.312445,-0.140146) , 
7, 2.03975, 1, 0, 0.507888,0.00289136)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272496,-0.017645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717817,0.016567) , 
5, 84.2319, 1, 0, 0.600582,0.0712983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399915,-0.0080396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18901,-0.0243557) , 
5, 138.898, 1, 0, 0.286362,-0.15595) , 
7, 2.20706, 1, 0, 0.506965,0.00359336)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12037,-0.0302067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309357,-0.013484) , 
5, 64.2459, 1, 0, 0.189622,-0.218739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744835,0.0177916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364737,-0.00941615) , 
7, 1.84011, 1, 0, 0.565941,0.0459143) , 
5, 77.6026, 1, 0, 0.501602,0.000666436)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.19911,-0.0220947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668988,0.0120822) , 
5, 77.7508, 1, 0, 0.571125,0.0474019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31485,-0.013059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160168,-0.0270767) , 
10, 0.411827, 1, 0, 0.213835,-0.20342) , 
5, 143.566, 1, 0, 0.488139,-0.0108552)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0805416,-0.0334248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196704,-0.0211342) , 
5, 53.9137, 1, 0, 0.137856,-0.24443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700608,0.0134883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341253,-0.00983755) , 
7, 2.03871, 1, 0, 0.560992,0.0406107) , 
5, 69.2912, 1, 0, 0.507077,0.00429115)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195463,-0.0208469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678572,0.0118322) , 
5, 75.8378, 1, 0, 0.589482,0.0552003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.135144,-0.0280502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313614,-0.0129744) , 
4, 108.639, 1, 0, 0.25076,-0.166223) , 
5, 138.246, 1, 0, 0.502934,-0.00137642)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.120775,-0.0229877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737023,0.0142981) , 
4, 81.8536, 1, 0, 0.627809,0.0739606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367931,-0.00718079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160034,-0.0213021) , 
6, 2.05089, 1, 0, 0.25144,-0.134884) , 
6, 1.56286, 1, 0, 0.509535,0.00833071)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360394,-0.00975804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76493,0.0148365) , 
4, 106.072, 1, 0, 0.610351,0.0500531) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0985905,-0.028039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290848,-0.011887) , 
5, 89.0022, 1, 0, 0.24627,-0.140241) , 
6, 1.56809, 1, 0, 0.49844,-0.00843901)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210667,-0.0165691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720998,0.0125054) , 
4, 95.4241, 1, 0, 0.585079,0.044857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168568,-0.0214624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297891,-0.00504606) , 
5, 206.763, 1, 0, 0.188479,-0.164184) , 
4, 150.48, 1, 0, 0.501974,0.00105331)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219237,-0.0177151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750306,0.0158454) , 
5, 78.8651, 1, 0, 0.620092,0.0691877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418449,-0.00602779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199527,-0.0197948) , 
5, 145.304, 1, 0, 0.320641,-0.108509) , 
7, 1.90029, 1, 0, 0.498791,-0.00279342)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183624,-0.0170614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708592,0.0106532) , 
4, 92.1558, 1, 0, 0.582006,0.0382494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187983,-0.0197861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321119,-0.000544789) , 
4, 297.635, 1, 0, 0.205168,-0.148766) , 
4, 145.982, 1, 0, 0.492058,-0.00638968)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173281,-0.0167387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764565,0.014203) , 
4, 90.1219, 1, 0, 0.620796,0.0621429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105812,-0.0258463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292053,-0.0102966) , 
5, 89.2606, 1, 0, 0.247116,-0.121244) , 
6, 1.56561, 1, 0, 0.505358,0.00549066)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239077,-0.0169115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689522,0.0122035) , 
5, 84.1168, 1, 0, 0.572379,0.0426385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114713,-0.0289077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295957,-0.0123219) , 
4, 108.466, 1, 0, 0.233396,-0.15413) , 
5, 146.361, 1, 0, 0.502067,0.00182473)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290496,-0.0104931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777473,0.0139118) , 
4, 101.054, 1, 0, 0.612072,0.0501649) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340459,-0.00650693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132122,-0.0225916) , 
6, 2.24023, 1, 0, 0.241903,-0.12049) , 
6, 1.56056, 1, 0, 0.496013,-0.00334051)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197654,-0.0144779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729738,0.0110637) , 
4, 92.0523, 1, 0, 0.599115,0.0441579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629192,0.0031041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169257,-0.0188425) , 
6, 1.18851, 1, 0, 0.212148,-0.138894) , 
4, 140.956, 1, 0, 0.49238,-0.00633247)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308283,-0.00781808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13715,-0.0260784) , 
10, 0.378355, 1, 0, 0.191858,-0.165987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808311,0.0192813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411458,-0.00594462) , 
7, 1.52115, 1, 0, 0.560237,0.0283155) , 
5, 79.916, 1, 0, 0.494406,-0.00640725)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649481,0.00834134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230935,-0.0213029) , 
5, 153.256, 1, 0, 0.589484,0.0345745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642469,0.00453162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188235,-0.0177526) , 
6, 1.1228, 1, 0, 0.232887,-0.127769) , 
4, 139.758, 1, 0, 0.494055,-0.00887029)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167224,-0.0159643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704838,0.00852) , 
4, 89.6151, 1, 0, 0.584857,0.0294901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185001,-0.0172613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484621,0.00173489) , 
0, 119.104, 1, 0, 0.214977,-0.124432) , 
4, 141.219, 1, 0, 0.485711,-0.0117684)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320942,-0.0127229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688275,0.0110286) , 
5, 91.9078, 1, 0, 0.566608,0.0277093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0917499,-0.02712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280259,-0.0125457) , 
4, 104.783, 1, 0, 0.219281,-0.139664) , 
5, 148.868, 1, 0, 0.496412,-0.00611725)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189304,-0.0177902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693213,0.0111121) , 
5, 72.974, 1, 0, 0.599737,0.0501774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222599,-0.0218107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316591,-0.00875997) , 
0, 43.8056, 1, 0, 0.297651,-0.0987705) , 
7, 2.21412, 1, 0, 0.508017,0.00495333)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145018,-0.0197709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697105,0.0109827) , 
5, 69.2115, 1, 0, 0.605282,0.0523877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413271,-0.00234327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23746,-0.0161293) , 
6, 1.25436, 1, 0, 0.295872,-0.0989367) , 
7, 2.14316, 1, 0, 0.507381,0.00450717)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329414,-0.00878421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761957,0.0127314) , 
4, 104.83, 1, 0, 0.596938,0.0387817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194571,-0.0160698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30821,0.00068701) , 
5, 219.355, 1, 0, 0.208033,-0.112108) , 
4, 143.208, 1, 0, 0.501075,0.00158787)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212493,-0.0148999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674626,0.00920768) , 
5, 77.3362, 1, 0, 0.587348,0.0407402) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165755,-0.0230597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286549,-0.00961203) , 
4, 113.2, 1, 0, 0.242456,-0.117945) , 
5, 142.683, 1, 0, 0.507494,0.00399946)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306053,-0.0105417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720104,0.012353) , 
5, 88.9532, 1, 0, 0.590573,0.0442262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286236,-0.0108963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123095,-0.0268985) , 
11, 0.817115, 1, 0, 0.249297,-0.117197) , 
5, 137.943, 1, 0, 0.502723,0.00267304)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693805,0.0107113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300708,-0.00735159) , 
6, 1.51121, 1, 0, 0.575767,0.0426113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395868,-0.00774017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236454,-0.0201432) , 
11, 0.780072, 1, 0, 0.34049,-0.0964201) , 
10, 0.630487, 1, 0, 0.499467,-0.00247598)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17994,-0.0143374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764044,0.0104819) , 
4, 92.6706, 1, 0, 0.609404,0.0341864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48262,-0.00232092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180413,-0.0157184) , 
4, 130.385, 1, 0, 0.270337,-0.0922897) , 
6, 1.46887, 1, 0, 0.492064,-0.00958289)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168044,-0.0175466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734706,0.012204) , 
5, 70.8545, 1, 0, 0.625785,0.0544983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363992,-0.00548393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218023,-0.0183998) , 
3, 1.41104, 1, 0, 0.318229,-0.0780123) , 
7, 1.93177, 1, 0, 0.502948,0.00157409)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66536,0.0095917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172004,-0.0150342) , 
6, 2.04682, 1, 0, 0.591342,0.0489053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429768,-0.00480128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237844,-0.0201377) , 
3, 1.38651, 1, 0, 0.371461,-0.0745836) , 
10, 0.581408, 1, 0, 0.509008,0.00266516)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180855,-0.0123499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784908,0.0121262) , 
4, 90.4281, 1, 0, 0.628045,0.0485861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519682,-0.000877409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189823,-0.0143217) , 
4, 132.253, 1, 0, 0.313707,-0.070621) , 
6, 1.36842, 1, 0, 0.504411,0.00170004)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658583,0.00710022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162547,-0.0175597) , 
4, 155.353, 1, 0, 0.579378,0.0273611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228007,-0.0181733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24734,0.00116386) , 
4, 211.042, 1, 0, 0.231349,-0.120466) , 
5, 142.683, 1, 0, 0.498648,-0.00692967)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173492,-0.0158094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734155,0.0108764) , 
5, 70.8545, 1, 0, 0.615885,0.0432717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450009,-0.00155488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279249,-0.0123628) , 
6, 1.23998, 1, 0, 0.340745,-0.0700749) , 
7, 1.80956, 1, 0, 0.498935,-0.004907)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231104,-0.0140703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665989,0.00727447) , 
5, 81.7632, 1, 0, 0.566481,0.0207154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195191,-0.0180211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244297,0.000635668) , 
4, 210.447, 1, 0, 0.204071,-0.112753) , 
5, 149.269, 1, 0, 0.489733,-0.00754909)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1725,-0.0166391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698723,0.0094326) , 
5, 71.0953, 1, 0, 0.613916,0.0424464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258858,-0.0127632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420659,0.00532738) , 
0, 100.607, 1, 0, 0.272847,-0.0894575) , 
7, 2.25039, 1, 0, 0.504531,0.000143273)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673923,0.00936581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323051,-0.00750705) , 
7, 2.176, 1, 0, 0.576332,0.0348702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429739,-0.00521336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252499,-0.0168556) , 
10, 0.794173, 1, 0, 0.345517,-0.0835294) , 
10, 0.610913, 1, 0, 0.495708,-0.00648696)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406275,-0.00367314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219052,-0.0192339) , 
10, 0.474546, 1, 0, 0.306032,-0.0928438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690749,0.00806529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2571,-0.010255) , 
5, 142.763, 1, 0, 0.566126,0.0228576) , 
5, 89.3037, 1, 0, 0.503697,-0.00491379)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660432,0.00776784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202222,-0.0121322) , 
6, 1.88466, 1, 0, 0.571802,0.0309932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402597,-0.00563668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21823,-0.0196956) , 
3, 1.32354, 1, 0, 0.334459,-0.0806797) , 
11, 0.681013, 1, 0, 0.498556,-0.00347002)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230247,-0.0116833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692187,0.00672524) , 
4, 95.9815, 1, 0, 0.574823,0.0168915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156424,-0.0164203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228169,0.000691203) , 
4, 261.703, 1, 0, 0.169094,-0.0986682) , 
6, 1.95182, 1, 0, 0.490742,-0.0070566)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43716,-0.00319513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668271,0.00894058) , 
0, 67.6368, 1, 0, 0.561097,0.0241038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372839,-0.00677367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240953,-0.0172417) , 
11, 0.7806, 1, 0, 0.324768,-0.0785508) , 
10, 0.697677, 1, 0, 0.502026,-0.0015548)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131755,-0.0163678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700463,0.00780597) , 
4, 82.6151, 1, 0, 0.601864,0.0320854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202134,-0.0140311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286939,0.00314047) , 
4, 275.94, 1, 0, 0.215655,-0.080812) , 
4, 142.1, 1, 0, 0.504161,0.00352488)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119456,-0.0195143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618469,0.00540322) , 
4, 79.781, 1, 0, 0.570329,0.0241271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2644,-0.016374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399967,-0.00545472) , 
1, 40.3488, 1, 0, 0.336361,-0.0812676) , 
11, 0.667428, 1, 0, 0.494905,-0.00984867)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367076,-0.00636111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.850384,0.0167474) , 
4, 108.948, 1, 0, 0.617303,0.0412766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423618,-0.00398478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178594,-0.0173769) , 
7, 2.79915, 1, 0, 0.37141,-0.0528918) , 
6, 1.22855, 1, 0, 0.498788,-0.00411058)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361967,-0.00698649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732891,0.0100584) , 
4, 106.302, 1, 0, 0.590676,0.0267552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.16863,-0.0144562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309841,0.00495878) , 
4, 280.054, 1, 0, 0.190757,-0.0786879) , 
4, 152.205, 1, 0, 0.504074,0.00392146)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357324,-0.0075682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648664,0.00840994) , 
5, 89.4149, 1, 0, 0.578664,0.0339358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458687,-0.000262707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30074,-0.0122147) , 
3, 0.550761, 1, 0, 0.345824,-0.0647635) , 
10, 0.611317, 1, 0, 0.499303,0.000295284)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128287,-0.0148258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769065,0.0110321) , 
4, 81.9987, 1, 0, 0.643959,0.0479268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543122,-0.000317495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210533,-0.0105094) , 
4, 133.928, 1, 0, 0.349928,-0.0442653) , 
6, 1.30422, 1, 0, 0.513015,0.00686984)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206209,-0.0137205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62271,0.0061516) , 
5, 73.4228, 1, 0, 0.573979,0.0292263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552855,0.00716238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315062,-0.0112072) , 
3, 0.256043, 1, 0, 0.341206,-0.0668837) , 
11, 0.664121, 1, 0, 0.499759,-0.00141825)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476419,-0.00201861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810907,0.0146565) , 
4, 115.666, 1, 0, 0.605669,0.0325119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822507,0.0151891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248301,-0.0102155) , 
6, 0.942642, 1, 0, 0.294822,-0.0578944) , 
4, 134.469, 1, 0, 0.504633,0.00312676)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0428829,-0.0272726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144596,-0.0111621) , 
4, 62.6266, 1, 0, 0.0838198,-0.130142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650876,0.00508383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167345,-0.0117188) , 
4, 160.545, 1, 0, 0.548488,0.0149357) , 
4, 75.6289, 1, 0, 0.494831,-0.00181699)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688397,0.00916488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196364,-0.0137867) , 
6, 1.87642, 1, 0, 0.598026,0.0361505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29552,-0.0110113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285416,0.0065179) , 
4, 257.217, 1, 0, 0.294578,-0.0691222) , 
5, 132.28, 1, 0, 0.513323,0.0067653)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233717,-0.0170856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43166,-0.00313916) , 
0, 43.6297, 1, 0, 0.391314,-0.0460215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750936,0.0118224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312279,-0.00418621) , 
5, 146.009, 1, 0, 0.63519,0.0512039) , 
0, 74.3094, 1, 0, 0.494212,-0.00499914)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222958,-0.0107245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774859,0.0113674) , 
5, 79.6302, 1, 0, 0.616156,0.0362221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504948,-0.000157774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264128,-0.0101876) , 
5, 122.605, 1, 0, 0.349543,-0.0488595) , 
7, 1.80677, 1, 0, 0.501693,-0.000305258)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324137,-0.00792033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0882982,-0.0274096) , 
10, 0.803201, 1, 0, 0.27976,-0.0807065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707993,0.00852095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280235,-0.00843479) , 
5, 134.696, 1, 0, 0.563803,0.0210309) , 
5, 87.0177, 1, 0, 0.50033,-0.00170371)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651651,0.00636096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215686,-0.00974637) , 
4, 159.222, 1, 0, 0.5816,0.0280882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335956,-0.010574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580635,0.00470352) , 
0, 113.802, 1, 0, 0.356364,-0.0660979) , 
10, 0.610989, 1, 0, 0.50366,-0.00450371)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488448,-0.00260373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180439,-0.0142064) , 
6, 1.84755, 1, 0, 0.390356,-0.0465133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721845,0.00877661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236319,-0.00872395) , 
4, 153.308, 1, 0, 0.614723,0.0334947) , 
0, 68.773, 1, 0, 0.502736,-0.00643902)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277777,-0.009189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.814735,0.0106866) , 
4, 100.486, 1, 0, 0.622455,0.0235893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325548,-0.00774676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333869,0.0139401) , 
4, 307.399, 1, 0, 0.326045,-0.0484305) , 
6, 1.33713, 1, 0, 0.495894,-0.00716164)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148325,-0.0166104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686555,0.00677474) , 
5, 71.2939, 1, 0, 0.586805,0.0200697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356548,0.000336145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226562,-0.0132493) , 
6, 1.09142, 1, 0, 0.262173,-0.0717752) , 
7, 2.27619, 1, 0, 0.491836,-0.00679912)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333603,-0.00667003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855615,0.0144284) , 
4, 106.915, 1, 0, 0.61408,0.0299304) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567237,-0.00101282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210375,-0.0122252) , 
4, 133.66, 1, 0, 0.378792,-0.0483468) , 
6, 1.19194, 1, 0, 0.492534,-0.0105064)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15224,-0.017627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597324,0.00469402) , 
5, 63.398, 1, 0, 0.560148,0.0209887) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363763,-0.00492568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185606,-0.0199261) , 
11, 0.800443, 1, 0, 0.298981,-0.0722379) , 
10, 0.73409, 1, 0, 0.503652,0.00082195)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0917815,-0.0182668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597765,0.00427282) , 
4, 74.1317, 1, 0, 0.547454,0.0167707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211907,-0.020101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146109,-0.0011532) , 
4, 143.33, 1, 0, 0.193082,-0.116713) , 
7, 2.9384, 1, 0, 0.503286,0.000133646)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160232,-0.0127216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0392589,-0.0306502) , 
10, 0.468603, 1, 0, 0.0832622,-0.140488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669502,0.00521557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329855,-0.00629814) , 
7, 1.88453, 1, 0, 0.523154,0.000101353) , 
5, 58.6225, 1, 0, 0.489281,-0.0107243)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671351,0.00700999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198364,-0.0125789) , 
4, 147.889, 1, 0, 0.588646,0.0259327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306836,-0.0102599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265566,0.00903982) , 
4, 221.71, 1, 0, 0.300861,-0.054687) , 
5, 132.28, 1, 0, 0.505892,0.00274997)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0878232,-0.0222136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101072,-0.0115272) , 
7, 1.84593, 1, 0, 0.0929376,-0.111149) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743151,0.00739678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304833,-0.00661412) , 
6, 1.37602, 1, 0, 0.54781,0.00738358) , 
4, 76.8639, 1, 0, 0.495328,-0.00629243)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228998,-0.012953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62473,0.00607105) , 
5, 79.9516, 1, 0, 0.553926,0.0186115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235481,-0.0254914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274545,-0.0112838) , 
11, 0.239494, 1, 0, 0.268023,-0.092952) , 
10, 0.744047, 1, 0, 0.490804,-0.00601959)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322634,-0.00453111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194009,-0.0184198) , 
7, 2.06754, 1, 0, 0.238934,-0.104269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619693,0.00489904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262342,-0.00784749) , 
5, 139.83, 1, 0, 0.531281,0.0118497) , 
0, 43.2237, 1, 0, 0.499769,-0.000666656)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304829,-0.0081561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711293,0.00821221) , 
5, 89.3834, 1, 0, 0.580559,0.0213798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255861,-0.0115538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278764,0.0113934) , 
4, 213.369, 1, 0, 0.259292,-0.0596258) , 
5, 138.526, 1, 0, 0.503488,0.00194676)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118911,-0.0134809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760425,0.00796457) , 
4, 81.1895, 1, 0, 0.630932,0.0284741) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49283,-9.29139e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195717,-0.00964557) , 
4, 131.087, 1, 0, 0.301066,-0.040664) , 
6, 1.39183, 1, 0, 0.50438,0.00194947)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645289,0.00546657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305062,-0.00561181) , 
4, 135.43, 1, 0, 0.545178,0.0157132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276843,-0.014246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327439,0.000304016) , 
8, 0.691925, 1, 0, 0.289244,-0.0704944) , 
11, 0.790285, 1, 0, 0.499149,0.00020901)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128723,-0.0218619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355567,-0.00268678) , 
7, 0.789057, 1, 0, 0.261716,-0.0649199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754232,0.00728344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338733,-0.00334779) , 
7, 1.89158, 1, 0, 0.560704,0.014339) , 
5, 84.4211, 1, 0, 0.50124,-0.00142423)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278311,-0.00677738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822079,0.010358) , 
4, 99.8256, 1, 0, 0.635179,0.0282556) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327316,-0.00702643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301961,0.0119001) , 
4, 292.736, 1, 0, 0.325534,-0.0424127) , 
6, 1.34016, 1, 0, 0.504723,-0.00151759)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0537999,-0.0234439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125148,-0.0121332) , 
4, 63.8218, 1, 0, 0.0852941,-0.101679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743618,0.00801841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394566,-0.00369038) , 
6, 1.19152, 1, 0, 0.550377,0.00929449) , 
4, 75.743, 1, 0, 0.498418,-0.00310331)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69876,0.00788503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454832,-0.00152481) , 
6, 1.20357, 1, 0, 0.580676,0.0207966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435021,-0.00275117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217107,-0.0129841) , 
5, 128.995, 1, 0, 0.352896,-0.0437726) , 
11, 0.667709, 1, 0, 0.506585,-0.000205938)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388603,-0.00404123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783131,0.00974221) , 
4, 107.37, 1, 0, 0.600676,0.0222013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875614,0.0175093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256592,-0.00882624) , 
6, 0.865254, 1, 0, 0.303113,-0.0442647) , 
4, 132.057, 1, 0, 0.497393,-0.0008687)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.10338,-0.020058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189596,-0.0051585) , 
7, 0.822067, 1, 0, 0.132316,-0.084736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639984,0.00485456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32838,-0.00529743) , 
4, 134.469, 1, 0, 0.543396,0.0120839) , 
5, 64.5209, 1, 0, 0.502228,0.00238764)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442831,-0.0020298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694731,0.0109345) , 
5, 93.8741, 1, 0, 0.627042,0.0487768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516216,1.6658e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302193,-0.00895114) , 
10, 0.714295, 1, 0, 0.454776,-0.0167363) , 
11, 0.338809, 1, 0, 0.512689,0.00528791)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112329,-0.0136842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584503,0.00354065) , 
4, 74.8004, 1, 0, 0.540119,0.0146983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553111,0.00581416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364547,-0.00996182) , 
2, 0.183765, 1, 0, 0.381609,-0.0572969) , 
3, 1.21989, 1, 0, 0.487828,-0.009052)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0651597,-0.020582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195505,-0.00632848) , 
4, 65.5032, 1, 0, 0.136463,-0.070817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713757,0.00649769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244836,-0.00746768) , 
4, 138.086, 1, 0, 0.561353,0.0158282) , 
4, 83.7447, 1, 0, 0.500731,0.00346578)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167973,-0.0193506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409398,-0.00400181) , 
7, 0.781634, 1, 0, 0.325854,-0.0579541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726909,0.00756684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328475,-0.00554925) , 
5, 129.715, 1, 0, 0.564285,0.0151458) , 
5, 91.3789, 1, 0, 0.50228,-0.00386405)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463888,-0.00172679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136875,-0.0138182) , 
6, 2.07547, 1, 0, 0.383543,-0.0299804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147592,-0.0128782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666432,0.00650094) , 
4, 83.0686, 1, 0, 0.611726,0.0286409) , 
0, 67.6515, 1, 0, 0.502578,0.00060029)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197749,-0.0156594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413716,-0.00327547) , 
7, 0.93703, 1, 0, 0.314267,-0.0543034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726256,0.00768491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301986,-0.00452915) , 
5, 132.045, 1, 0, 0.561819,0.0196997) , 
5, 92.1814, 1, 0, 0.495157,-0.000228317)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679194,0.00499033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280968,-0.0109837) , 
5, 149.4, 1, 0, 0.614921,0.0140676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223514,-0.00910553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284532,0.0113908) , 
4, 293.267, 1, 0, 0.228617,-0.0509284) , 
6, 1.56809, 1, 0, 0.492961,-0.00645224)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643932,0.00528656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278581,-0.00530801) , 
4, 138.195, 1, 0, 0.548437,0.0169136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396554,-0.0153355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385053,-0.00361264) , 
2, 0.518155, 1, 0, 0.388818,-0.0491328) , 
3, 1.20394, 1, 0, 0.495382,-0.00503945)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0678015,-0.0205675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66055,0.00545276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370488,-0.00311495) , 
7, 1.82958, 1, 0, 0.540182,0.010636) , 
4, 66.0657, 1, 0, 0.504817,0.00166042)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0819875,-0.016129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670632,0.00438835) , 
4, 70.5101, 1, 0, 0.603286,0.0177779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29097,-0.00994369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241935,0.00534546) , 
4, 217.105, 1, 0, 0.279254,-0.0404807) , 
4, 134.956, 1, 0, 0.503788,-0.000111063)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726832,0.00936341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414182,-0.00219428) , 
7, 1.7998, 1, 0, 0.610073,0.029246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155724,-0.014472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481721,-0.00103454) , 
5, 78.4483, 1, 0, 0.419373,-0.0212142) , 
10, 0.408679, 1, 0, 0.504008,0.00118061)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659949,0.00920904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483813,-0.00082081) , 
10, 0.355385, 1, 0, 0.551447,0.019274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278832,-0.0137662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472221,-0.00150477) , 
1, 43.816, 1, 0, 0.362349,-0.0558932) , 
3, 1.40328, 1, 0, 0.50285,-4.36918e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257788,-0.0131358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491832,-0.0011226) , 
6, 0.982988, 1, 0, 0.348845,-0.0540729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869061,0.0134971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399696,-0.00260161) , 
6, 1.1567, 1, 0, 0.567058,0.0167765) , 
4, 106.465, 1, 0, 0.502772,-0.00409593)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362858,-0.00633769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706061,0.00659681) , 
5, 95.0404, 1, 0, 0.579384,0.0121285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234338,-0.0109783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2399,0.00860339) , 
4, 207.336, 1, 0, 0.23523,-0.0526077) , 
5, 140.368, 1, 0, 0.495432,-0.00366295)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316916,-0.0016304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241259,-0.0128289) , 
6, 1.01375, 1, 0, 0.269326,-0.0556259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727798,0.00766487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345367,-0.0040264) , 
5, 126.955, 1, 0, 0.568114,0.0180522) , 
5, 86.9559, 1, 0, 0.501212,0.00155472)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.053354,-0.0196662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582668,0.00481244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378079,-0.00675421) , 
3, 1.63449, 1, 0, 0.549039,0.018956) , 
4, 64.474, 1, 0, 0.515155,0.0117618)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615181,0.00454733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229853,-0.0120541) , 
7, 2.94006, 1, 0, 0.57346,0.016744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259264,-0.0117971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425507,-0.00143959) , 
1, 42.211, 1, 0, 0.340277,-0.0436236) , 
10, 0.661152, 1, 0, 0.507365,-0.000366861)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.100542,-0.0201371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202361,-0.00275181) , 
9, 0.163264, 1, 0, 0.137443,-0.0750278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595333,0.00350902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211531,-0.0101104) , 
7, 2.93889, 1, 0, 0.547528,0.0119722) , 
5, 63.398, 1, 0, 0.509462,0.00389651)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616184,0.00320307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263075,-0.0125859) , 
7, 2.95132, 1, 0, 0.589165,0.0115076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388089,-0.00659147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296014,0.0144664) , 
4, 261.164, 1, 0, 0.383383,-0.0355508) , 
10, 0.488392, 1, 0, 0.488986,-0.0114013)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470939,0.00155729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272621,-0.0129731) , 
10, 0.411492, 1, 0, 0.35421,-0.0430683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.841345,0.0117434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39686,-0.00241329) , 
7, 1.53458, 1, 0, 0.550922,0.0113121) , 
5, 94.3855, 1, 0, 0.498151,-0.00327614)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652021,0.00510033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345651,-0.00518176) , 
5, 131.447, 1, 0, 0.570214,0.0139875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232954,-0.0136311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377368,-0.00202153) , 
1, 40.887, 1, 0, 0.307083,-0.0476242) , 
10, 0.674071, 1, 0, 0.492146,-0.00429201)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0918178,-0.0182752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270441,-0.00459626) , 
6, 0.581367, 1, 0, 0.227817,-0.0447116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83502,0.00881893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381126,-0.00215516) , 
6, 1.23549, 1, 0, 0.576508,0.0140061) , 
4, 97.1109, 1, 0, 0.498012,0.000787624)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206999,-0.0131302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384996,-0.00190397) , 
4, 106.678, 1, 0, 0.31337,-0.0385192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724903,0.00587635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306254,-0.00395193) , 
5, 132.246, 1, 0, 0.56839,0.0137315) , 
5, 90.6151, 1, 0, 0.505028,0.00074945)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159421,-0.0145353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612545,0.0035442) , 
5, 64.2603, 1, 0, 0.573638,0.0132989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471043,0.00462352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322407,-0.00869836) , 
2, 0.215165, 1, 0, 0.338511,-0.044935) , 
11, 0.657447, 1, 0, 0.493943,-0.00643922)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12423,-0.012934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672683,0.00570968) , 
5, 63.5102, 1, 0, 0.596862,0.022921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303755,-0.00691237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295596,0.00742317) , 
8, 1.05309, 1, 0, 0.302241,-0.0276018) , 
5, 131.863, 1, 0, 0.513958,0.00870421)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205094,-0.0133756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425803,-0.00153654) , 
4, 106.146, 1, 0, 0.341636,-0.0354575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.871866,0.0125778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460714,-0.00076844) , 
7, 1.3276, 1, 0, 0.563327,0.0119726) , 
5, 93.8741, 1, 0, 0.501791,-0.00119289)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0514793,-0.0214276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705673,0.00509594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323624,-0.00486784) , 
6, 1.32887, 1, 0, 0.529693,0.00164671) , 
4, 66.3056, 1, 0, 0.491986,-0.00638216)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644645,0.00586878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331074,-0.00386015) , 
5, 130.856, 1, 0, 0.552449,0.0181443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272214,-0.0134705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447847,-0.00231499) , 
1, 34.8488, 1, 0, 0.390117,-0.0391648) , 
3, 1.32354, 1, 0, 0.507482,0.0022693)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208031,-0.0159604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295954,-0.000320243) , 
4, 119.852, 1, 0, 0.244105,-0.059509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638955,0.00425337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370546,-0.0059146) , 
11, 0.680942, 1, 0, 0.555609,0.00714092) , 
5, 84.4211, 1, 0, 0.493607,-0.00612502)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661761,0.00458028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282918,-0.00425077) , 
4, 138.911, 1, 0, 0.567119,0.0147388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315912,-0.00379054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194288,-0.0190772) , 
2, 1.52648, 1, 0, 0.287437,-0.0433878) , 
10, 0.744072, 1, 0, 0.510121,0.00289278)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397471,-0.00440607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793063,0.0084113) , 
5, 97.7125, 1, 0, 0.615655,0.0140876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38596,0.00577486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296576,-0.00790286) , 
6, 0.928942, 1, 0, 0.315664,-0.0366369) , 
7, 1.89535, 1, 0, 0.495759,-0.00618524)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288698,-0.00578683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282079,-0.0241777) , 
1, 62.8405, 1, 0, 0.28798,-0.0502403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.867465,0.0117379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411404,-0.0018423) , 
6, 1.14698, 1, 0, 0.575814,0.0151738) , 
4, 102.124, 1, 0, 0.500426,-0.00195921)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563796,0.00264544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645162,0.0139579) , 
9, 0.694612, 1, 0, 0.592155,0.0423101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137584,-0.0290181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488533,-0.00175736) , 
7, 0.540703, 1, 0, 0.475182,-0.0161248) , 
2, 0.390699, 1, 0, 0.503853,-0.0018017)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597287,0.00375737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256793,-0.00771147) , 
7, 2.79708, 1, 0, 0.550559,0.0128289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296388,0.00288407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264342,-0.012469) , 
9, -1.19875, 1, 0, 0.274068,-0.047566) , 
10, 0.764117, 1, 0, 0.498307,0.00141528)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136988,-0.00171306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0533149,-0.0207618) , 
2, 0.740033, 1, 0, 0.0849976,-0.0598529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631738,0.00306322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287874,-0.00544685) , 
5, 136.163, 1, 0, 0.542887,0.00501379) , 
4, 77.521, 1, 0, 0.491503,-0.0022656)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.120134,-0.0107494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637397,0.0028561) , 
4, 81.0614, 1, 0, 0.560442,0.00760636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.139016,-0.0150604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140128,-0.00105905) , 
10, 0.579312, 1, 0, 0.139501,-0.056502) , 
6, 2.20686, 1, 0, 0.49937,-0.00169474)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450877,0.00436682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343663,-0.00770319) , 
2, 0.271334, 1, 0, 0.360391,-0.0365804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789526,0.00789049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299238,-0.00487305) , 
4, 133.141, 1, 0, 0.550462,0.0104197) , 
4, 107.785, 1, 0, 0.48874,-0.0048426)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252223,-0.0158761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183567,0.00374952) , 
4, 139.146, 1, 0, 0.232128,-0.0770267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617583,0.00333372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300564,-0.0049525) , 
4, 134.956, 1, 0, 0.523211,0.00537588) , 
9, -2.41098, 1, 0, 0.495966,-0.00233701)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460258,0.00175831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364275,-0.00664407) , 
7, 1.50589, 1, 0, 0.395198,-0.0279502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322363,-0.00533357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674199,0.00682137) , 
4, 100.93, 1, 0, 0.603805,0.023275) , 
1, 44.4286, 1, 0, 0.494652,-0.00352837)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519692,0.000895975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2971,-0.011041) , 
10, 0.41504, 1, 0, 0.388029,-0.0360865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592823,0.00420142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389087,-0.00714712) , 
2, 1.52256, 1, 0, 0.555288,0.0126182) , 
5, 98.3037, 1, 0, 0.50111,-0.00315796)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213676,-0.00184598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0955557,-0.017966) , 
6, 1.12007, 1, 0, 0.145097,-0.0582512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607206,0.00481641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431977,-0.00370872) , 
3, 1.40328, 1, 0, 0.565873,0.017528) , 
5, 64.966, 1, 0, 0.525012,0.0101692)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577155,0.00254015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346801,-0.00512577) , 
11, 0.654421, 1, 0, 0.499809,7.69962e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277349,-0.0175835) , 
3, 2.06503, 1, 0, 0.486765,-0.00625862)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471892,-0.00349312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785686,0.00955388) , 
4, 115.835, 1, 0, 0.605025,0.0112296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194774,-0.00946545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268694,0.0123915) , 
5, 218.833, 1, 0, 0.203457,-0.039854) , 
4, 141.219, 1, 0, 0.499517,-0.00219211)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105813,-0.0188892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158706,-0.00586705) , 
9, 0.187814, 1, 0, 0.125907,-0.0730835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598913,0.00287317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336668,-0.00494612) , 
9, 1.70078, 1, 0, 0.546681,0.0073553) , 
5, 65.8391, 1, 0, 0.499054,-0.00174961)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591784,0.0040841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384507,-0.00267838) , 
5, 124.788, 1, 0, 0.520094,0.0101363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178526,-0.00486391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263103,-0.030356) , 
0, 72.9062, 1, 0, 0.209607,-0.0860698) , 
11, 0.906886, 1, 0, 0.498259,0.00337052)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647044,0.00387831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186405,-0.00703721) , 
6, 2.04377, 1, 0, 0.577489,0.013527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28619,0.00565166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340577,-0.00752441) , 
8, -1.11442, 1, 0, 0.331042,-0.0309006) , 
11, 0.680807, 1, 0, 0.500041,-0.000434728)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650526,0.00682701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465573,-0.00114278) , 
7, 1.34255, 1, 0, 0.536097,0.00891475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29932,-0.0107945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53369,0.00219522) , 
0, 83.4892, 1, 0, 0.353539,-0.0478248) , 
2, 1.53819, 1, 0, 0.504624,-0.000867061)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402461,-0.00358244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571896,0.00364815) , 
4, 109.905, 1, 0, 0.513063,0.00594037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257056,-0.0172731) , 
3, 2.20855, 1, 0, 0.504762,0.00231197)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437592,-0.019802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549312,0.00098201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284168,-0.00846883) , 
11, 0.790545, 1, 0, 0.500452,-0.00427253) , 
3, 0.0399579, 1, 0, 0.498577,-0.00807476)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389697,-0.0043304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62427,0.004027) , 
5, 97.4069, 1, 0, 0.542482,0.00656581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228021,-0.0106584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187862,0.00333964) , 
5, 196.96, 1, 0, 0.216493,-0.0457975) , 
7, 2.89407, 1, 0, 0.50097,-0.000102138)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545915,-0.000180468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520523,0.00849864) , 
8, 0.762268, 1, 0, 0.539253,0.0129779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34822,-0.00856664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644539,0.00569032) , 
1, 62.8123, 1, 0, 0.391369,-0.0399339) , 
2, 1.22789, 1, 0, 0.498761,-0.00150983)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582158,0.00341127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206314,-0.00909678) , 
7, 2.97213, 1, 0, 0.541212,0.0122341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47887,-0.00177501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240914,-0.0118299) , 
11, 0.660786, 1, 0, 0.385907,-0.0326843) , 
2, 1.33151, 1, 0, 0.504774,0.00169523)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337626,0.000573037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217466,-0.014622) , 
6, 1.29988, 1, 0, 0.250984,-0.0721461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522143,0.0011121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796047,0.0144589) , 
0, 130.242, 1, 0, 0.541101,0.0116954) , 
0, 43.7021, 1, 0, 0.509582,0.00258677)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449949,0.0032439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309909,-0.00949534) , 
9, -0.720832, 1, 0, 0.343413,-0.0389461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734372,0.00431773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309732,-0.00383601) , 
5, 130.592, 1, 0, 0.55952,0.00553875) , 
5, 92.6409, 1, 0, 0.504713,-0.00574325)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330633,-0.00709884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547095,0.00134843) , 
0, 72.4312, 1, 0, 0.387124,-0.0324013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.120298,-0.0148614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658922,0.00606894) , 
5, 63.7819, 1, 0, 0.618151,0.0260695) , 
1, 44.8588, 1, 0, 0.496093,-0.00482235)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129472,-0.00849124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.792319,0.00728191) , 
4, 82.3873, 1, 0, 0.612638,0.018679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409267,-0.00733373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420019,0.00393364) , 
8, 0.824787, 1, 0, 0.413231,-0.0215723) , 
6, 1.09635, 1, 0, 0.49658,-0.00474778)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402136,-0.0188188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57341,0.00150393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328848,-0.00551477) , 
11, 0.671029, 1, 0, 0.493769,-0.00433252) , 
3, 0.0478422, 1, 0, 0.490422,-0.0085143)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430712,-0.0186832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597462,0.00295647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178379,-0.00576303) , 
4, 150.363, 1, 0, 0.502811,0.00675761) , 
3, 0.0400427, 1, 0, 0.500496,0.00260017)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345648,-0.00200808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.870895,0.0103911) , 
4, 107.259, 1, 0, 0.621564,0.0220331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505499,0.00311988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34528,-0.00671202) , 
7, 1.5068, 1, 0, 0.396043,-0.0257668) , 
6, 1.15134, 1, 0, 0.497631,-0.00423492)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39499,-0.00116424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222746,-0.0160348) , 
2, 1.53892, 1, 0, 0.360568,-0.0258604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773956,0.00742865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214293,-0.00318237) , 
4, 146.875, 1, 0, 0.597706,0.0237466) , 
4, 107.08, 1, 0, 0.520952,0.00769035)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680913,0.00560166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23363,-0.00940969) , 
4, 140.755, 1, 0, 0.586213,0.0139599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326212,-0.00610601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284796,0.0151513) , 
4, 243.345, 1, 0, 0.321968,-0.02375) , 
5, 128.326, 1, 0, 0.502142,0.00196223)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35649,-0.0021838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384542,-0.0186143) , 
0, 90.2464, 1, 0, 0.360968,-0.0309586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794747,0.00805778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319856,-0.00313243) , 
4, 133.149, 1, 0, 0.566097,0.0150558) , 
4, 107.785, 1, 0, 0.498628,-7.87626e-05)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585732,0.00173114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691275,0.0143749) , 
11, 0.226172, 1, 0, 0.607276,0.0247035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45465,-0.00426208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416703,0.00293818) , 
8, 0.866528, 1, 0, 0.445652,-0.0150745) , 
11, 0.292235, 1, 0, 0.492662,-0.00350466)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676187,0.00702795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313203,-0.00825876) , 
5, 135.785, 1, 0, 0.600796,0.0207972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34035,-0.00828946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206446,0.00860969) , 
7, 2.57631, 1, 0, 0.309239,-0.028445) , 
4, 132.829, 1, 0, 0.50156,0.00403689)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639313,0.00641109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414966,-0.0086715) , 
3, 1.83382, 1, 0, 0.616779,0.0280401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166876,-0.0156092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454866,-0.00226398) , 
0, 43.0017, 1, 0, 0.41946,-0.0234643) , 
10, 0.41863, 1, 0, 0.506341,-0.000786495)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407914,0.00190682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343125,-0.00812596) , 
6, 1.00935, 1, 0, 0.367242,-0.0287746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700834,0.00559555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268304,-0.00299751) , 
7, 2.44195, 1, 0, 0.559052,0.0153125) , 
5, 94.8054, 1, 0, 0.506832,0.00330998)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303392,-0.0104884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389989,0.000334388) , 
9, 0.19786, 1, 0, 0.340481,-0.0334646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682286,0.00355894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213583,-0.00699842) , 
5, 149.524, 1, 0, 0.555588,0.00426375) , 
5, 94.8054, 1, 0, 0.493748,-0.00658246)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402403,-0.017979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682315,0.0109462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481495,-0.00173686) , 
11, 0.0698028, 1, 0, 0.494852,-0.0054646) , 
3, 0.0478422, 1, 0, 0.49108,-0.00990905)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151163,-0.00347029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11285,-0.0165963) , 
6, 1.00177, 1, 0, 0.128852,-0.0569995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735669,0.00389317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414099,-0.0031118) , 
7, 1.42764, 1, 0, 0.529532,-0.00558422) , 
5, 66.0126, 1, 0, 0.48417,-0.0114051)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261653,-0.0153538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385791,-0.00240603) , 
4, 111.638, 1, 0, 0.32696,-0.0577693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642918,0.00589963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467579,-0.00247735) , 
11, 0.32888, 1, 0, 0.527663,0.00178409) , 
1, 30.7409, 1, 0, 0.491181,-0.00904083)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562151,-9.06762e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136109,-0.0111721) , 
4, 165.982, 1, 0, 0.502928,-0.00847367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33721,0.0178331) , 
4, 295.441, 1, 0, 0.49843,-0.00529954)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0637325,-0.0155403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711578,0.00471692) , 
4, 64.005, 1, 0, 0.632777,0.0158283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383147,-0.0131794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386838,-0.00181383) , 
3, 0.192698, 1, 0, 0.386369,-0.020698) , 
6, 1.19932, 1, 0, 0.506583,-0.00287806)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266645,-0.00317115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52212,-0.0207628) , 
4, 98.7853, 1, 0, 0.307293,-0.0397636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851904,0.00757871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358981,-0.00308526) , 
6, 1.24955, 1, 0, 0.564396,0.00456041) , 
4, 103.413, 1, 0, 0.494875,-0.00742483)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203268,-0.0130006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535072,0.00467534) , 
0, 41.0349, 1, 0, 0.502845,0.0167067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368523,-0.0074112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55717,-6.42321e-05) , 
4, 108.639, 1, 0, 0.495855,-0.0152254) , 
9, -0.636175, 1, 0, 0.49848,-0.00323275)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343808,-0.0070546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581106,0.003574) , 
1, 27.6977, 1, 0, 0.560935,0.0149056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565195,0.00778227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359706,-0.00717248) , 
10, 0.119532, 1, 0, 0.383146,-0.0306741) , 
3, 1.31556, 1, 0, 0.509797,0.00179536)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196313,-0.0271565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356513,-0.00335904) , 
4, 123.157, 1, 0, 0.278031,-0.0712736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659852,0.00395518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313635,-0.00314699) , 
7, 1.91192, 1, 0, 0.514575,0.00437139) , 
7, 0.614463, 1, 0, 0.500851,-1.72554e-05)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625639,0.00197607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440101,-0.00474919) , 
7, 1.35319, 1, 0, 0.515023,-0.0139184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544184,0.0150319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153825,-0.0058316) , 
6, 2.1486, 1, 0, 0.357366,0.0391789) , 
8, 1.26238, 1, 0, 0.49322,-0.00657543)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642244,0.00356576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218224,-0.00637075) , 
4, 143.116, 1, 0, 0.54066,0.00671716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265007,-0.0129194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174245,0.0100342) , 
4, 139.44, 1, 0, 0.236633,-0.0515932) , 
7, 2.81382, 1, 0, 0.497485,-0.0015635)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265912,-0.0112674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376996,-0.0015303) , 
4, 116.211, 1, 0, 0.318821,-0.037903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739908,0.00651685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328343,-0.000549116) , 
5, 130.571, 1, 0, 0.575587,0.020796) , 
5, 92.6409, 1, 0, 0.506411,0.00498178)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559729,0.000744001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408865,0.00907693) , 
8, 1.20014, 1, 0, 0.536305,0.0121473) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394716,-0.0166512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313527,-0.00397924) , 
11, 0.239555, 1, 0, 0.333993,-0.0425282) , 
3, 1.6184, 1, 0, 0.50004,0.00234662)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636342,0.00247499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152257,-0.0117787) , 
6, 2.1496, 1, 0, 0.576778,0.00375003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315765,-0.0101674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178296,0.0062321) , 
6, 1.68588, 1, 0, 0.266795,-0.0331647) , 
5, 135.396, 1, 0, 0.495452,-0.00593471)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353067,-0.00268759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626396,0.00528545) , 
4, 103.415, 1, 0, 0.557277,0.0180271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463924,-0.00826356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183078,0.0047841) , 
6, 1.68747, 1, 0, 0.380374,-0.0275614) , 
2, 1.22786, 1, 0, 0.506607,0.00496922)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685655,0.00551781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45316,-0.00246528) , 
5, 124.631, 1, 0, 0.607123,0.0154054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312973,-0.00606651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501368,-0.000501875) , 
1, 39.3522, 1, 0, 0.42019,-0.0178115) , 
10, 0.355168, 1, 0, 0.489648,-0.00546918)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714002,0.0151265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524072,-0.00407061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456098,0.0020071) , 
2, 0.836881, 1, 0, 0.493281,-0.00816085) , 
10, 0.0432746, 1, 0, 0.503039,-0.0040039)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180689,-0.0130161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0921804,-0.00140018) , 
6, 1.40692, 1, 0, 0.148814,-0.0504331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648593,0.00339141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323844,-0.0046069) , 
4, 133.534, 1, 0, 0.544404,0.00473964) , 
5, 72.0331, 1, 0, 0.492576,-0.00248887)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578834,0.00932579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406518,-0.000189399) , 
3, 1.22048, 1, 0, 0.520951,0.0373481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540415,0.00175919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361883,-0.00800332) , 
2, 1.37138, 1, 0, 0.500137,-0.00205632) , 
8, -0.678989, 1, 0, 0.505914,0.00888039)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459009,-0.0148082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0644631,-0.0171118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523962,0.000595999) , 
4, 65.0565, 1, 0, 0.495784,-0.00107899) , 
3, 0.0637884, 1, 0, 0.493929,-0.00547573)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404214,-0.00183543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472134,-0.0195319) , 
0, 96.0479, 1, 0, 0.412814,-0.0240484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791867,0.00722176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267862,-0.00358142) , 
4, 137.284, 1, 0, 0.55362,0.0123426) , 
4, 111.998, 1, 0, 0.500827,-0.00130147)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288275,-0.00466523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579268,0.00337629) , 
5, 86.9371, 1, 0, 0.517207,0.00964958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369513,0.00507493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285963,-0.0160864) , 
8, -0.349644, 1, 0, 0.314013,-0.0549318) , 
2, 1.88165, 1, 0, 0.501641,0.00470232)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647799,0.00425868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251229,-0.00997091) , 
5, 176.736, 1, 0, 0.611461,0.0163841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275888,-0.00730567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313294,0.0123294) , 
4, 293.378, 1, 0, 0.27944,-0.0293879) , 
4, 134.956, 1, 0, 0.506561,0.00192273)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0974811,-0.0200398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844644,0.00513818) , 
5, 76.7861, 1, 0, 0.313545,-0.0587632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222555,-0.00976927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540093,0.0021816) , 
0, 39.1438, 1, 0, 0.515839,0.0069604) , 
7, 0.687002, 1, 0, 0.498138,0.00120947)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28977,-0.00551656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305215,0.0127743) , 
10, 0.324315, 1, 0, 0.300052,0.034428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538904,-0.000950539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374466,-0.00925435) , 
2, 1.65807, 1, 0, 0.518523,-0.0111439) , 
8, -1.40846, 1, 0, 0.493364,-0.00589605)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634769,0.00461629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453097,-0.00181935) , 
6, 1.07823, 1, 0, 0.529633,0.00319084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219878,-0.00192348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267808,-0.0237536) , 
1, 49.7375, 1, 0, 0.236273,-0.057511) , 
10, 0.850337, 1, 0, 0.500396,-0.00285898)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551929,-1.29033e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128863,-0.0102566) , 
6, 2.22609, 1, 0, 0.497613,-0.00687714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314992,0.015144) , 
4, 285.624, 1, 0, 0.490836,-0.00327215)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251116,-0.0143813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935309,0.0170869) , 
5, 104.99, 1, 0, 0.404443,-0.0402173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721838,0.00642785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426304,-0.000404064) , 
7, 1.42708, 1, 0, 0.51991,0.00846517) , 
7, 0.83102, 1, 0, 0.50435,0.00190472)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.138716,-0.0193091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152605,-0.00602674) , 
2, 0.803618, 1, 0, 0.145568,-0.0791014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366156,-0.00490309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592429,0.00115639) , 
4, 108.639, 1, 0, 0.51285,-0.00609961) , 
8, -2.07702, 1, 0, 0.490757,-0.0104909)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659494,0.00446764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170341,-0.0104153) , 
4, 151.105, 1, 0, 0.580764,0.0122097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397637,-0.00882661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1955,0.00675834) , 
6, 1.65464, 1, 0, 0.325858,-0.0244741) , 
5, 127.779, 1, 0, 0.497862,0.00027914)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382994,0.0118375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575407,0.00170243) , 
8, -1.32466, 1, 0, 0.553324,0.0167441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527105,0.00743753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321671,-0.00647002) , 
11, 0.185922, 1, 0, 0.352427,-0.02318) , 
3, 1.41777, 1, 0, 0.502502,0.00664419)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654518,0.00383993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383728,-0.00245064) , 
6, 1.23561, 1, 0, 0.524699,0.00268628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253549,-0.01411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404377,-0.00216767) , 
4, 108.639, 1, 0, 0.347415,-0.0382974) , 
3, 1.48218, 1, 0, 0.485423,-0.00639345)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363217,-0.00210565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.895746,0.0120242) , 
4, 110, 1, 0, 0.617816,0.0193292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436216,-0.00660114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462221,0.00227716) , 
8, 0.741103, 1, 0, 0.44543,-0.021722) , 
6, 1.02448, 1, 0, 0.509057,-0.00657015)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449789,-0.0136465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50219,-0.00125758) , 
3, 0.0479307, 1, 0, 0.500328,-0.00986423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328499,0.0153776) , 
4, 278.817, 1, 0, 0.494704,-0.00644764)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571273,0.000408179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133472,-0.0082381) , 
6, 2.20572, 1, 0, 0.510309,-0.00380807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288273,0.00218775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443089,0.0226116) , 
0, 63.6266, 1, 0, 0.345052,0.057945) , 
9, 2.45296, 1, 0, 0.498836,0.000479146)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548374,-0.000714937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247857,-0.013463) , 
11, 0.83713, 1, 0, 0.504245,-0.0139578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617004,0.00728638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148644,-0.00425384) , 
6, 2.12836, 1, 0, 0.48076,0.0252345) , 
8, 0.720625, 1, 0, 0.497595,-0.00285913)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623809,0.0175271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30428,0.00350354) , 
5, 121.645, 1, 0, 0.416981,0.0560119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540291,-0.000581602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197434,-0.0164937) , 
9, 2.86866, 1, 0, 0.524561,-0.00808808) , 
9, -1.63809, 1, 0, 0.506011,0.00296485)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412985,-0.0146689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42735,-0.00143255) , 
3, 0.143687, 1, 0, 0.425761,-0.0177321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8961,0.0115537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416541,-2.75558e-06) , 
6, 1.04047, 1, 0, 0.542427,0.0132803) , 
4, 113.122, 1, 0, 0.498043,0.00148217)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311225,-0.00659812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556931,0.000313149) , 
5, 91.4399, 1, 0, 0.493242,-0.00841949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360725,0.01731) , 
4, 295.35, 1, 0, 0.489562,-0.00507912)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1549,-0.0158577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208437,0.0063571) , 
5, 119.094, 1, 0, 0.181223,-0.036144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477926,0.0201724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537076,0.00179074) , 
8, -1.51504, 1, 0, 0.535382,0.0135604) , 
8, -1.84677, 1, 0, 0.506947,0.0095697)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568813,-0.000166837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197589,-0.00790358) , 
5, 148.712, 1, 0, 0.49732,-0.00907174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320235,0.0120204) , 
5, 270.241, 1, 0, 0.490868,-0.00622832)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496791,0.00938256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585564,0.00174382) , 
9, -1.47108, 1, 0, 0.568904,0.0192135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378311,-0.000753273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483782,-0.0191859) , 
1, 64.9003, 1, 0, 0.394218,-0.0185153) , 
3, 1.23583, 1, 0, 0.511923,0.00690674)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578569,0.0025209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654237,0.0146183) , 
2, 0.643499, 1, 0, 0.584875,0.0203486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466975,-0.0112131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432793,-0.00056705) , 
3, 0.127837, 1, 0, 0.435626,-0.00820154) , 
2, 0.709501, 1, 0, 0.501119,0.00432675)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0520113,-0.0172837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648962,0.00274592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335068,-0.00332291) , 
4, 131.601, 1, 0, 0.533783,0.00360742) , 
4, 64.4544, 1, 0, 0.50258,-0.000601196)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348951,-0.00467347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563894,0.00288253) , 
1, 32.1761, 1, 0, 0.517087,0.00598373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289145,-0.0107735) , 
2, 1.99328, 1, 0, 0.50372,0.00212474)    );
   return;
};
 
// Clean up
inline void ReadBDT_200_300_2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_200_300_2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
