// Class: ReadBDT_175_325_2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_175_325_2
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/07       [396295]
Creator        : guerrero
Date           : Wed May 29 02:01:31 2019
Host           : Linux cmsbuild92.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/guerrero/Run2/HH2019/newcommit/CMSSW_10_2_5/src/bbbbAnalysis/mltraining/BackgroundRejection
Training events: 24696
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "175" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "325" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "5.000000e-02" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
HH_b3_pt                      HH_b3_pt                      HH_b3_pt                      HH_b3_pt                                                        'F'    [25.15625,694.5]
HH_b4_pt                      HH_b4_pt                      HH_b4_pt                      HH_b4_pt                                                        'F'    [25,445]
JJ_j1_qgl                     JJ_j1_qgl                     JJ_j1_qgl                     JJ_j1_qgl                                                       'F'    [-1,1]
JJ_j2_qgl                     JJ_j2_qgl                     JJ_j2_qgl                     JJ_j2_qgl                                                       'F'    [-1,1]
H1_m                          H1_m                          H1_m                          H1_m                                                            'F'    [15.9633493423,1959.92297363]
H2_m                          H2_m                          H2_m                          H2_m                                                            'F'    [18.9820747375,1430.10205078]
H1_bb_deltaR                  H1_bb_deltaR                  H1_bb_deltaR                  H1_bb_deltaR                                                    'F'    [0.398338407278,5.05964946747]
H2_bb_deltaR                  H2_bb_deltaR                  H2_bb_deltaR                  H2_bb_deltaR                                                    'F'    [0.402140974998,5.04085159302]
JJ_m                          JJ_m                          JJ_m                          JJ_m                                                            'F'    [22.3599529266,6316.22167969]
j1j2_deltaEta                 j1j2_deltaEta                 j1j2_deltaEta                 j1j2_deltaEta                                                   'F'    [0.0109348297119,9.580078125]
abs(costh_JJ_j1_cm)           abs_costh_JJ_j1_cm            abs_costh_JJ_j1_cm            abs_costh_JJ_j1_cm                                              'F'    [0.000248397875112,0.999988436699]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_175_325_2Node
   
#ifndef BDT_175_325_2Node__def
#define BDT_175_325_2Node__def
   
class BDT_175_325_2Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_175_325_2Node ( BDT_175_325_2Node* left,BDT_175_325_2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_175_325_2Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_175_325_2Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_175_325_2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_175_325_2Node*   fLeft;     // pointer to the left daughter node
   BDT_175_325_2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_175_325_2Node::~BDT_175_325_2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_175_325_2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_175_325_2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_175_325_2 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_175_325_2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_175_325_2" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HH_b3_pt", "HH_b4_pt", "JJ_j1_qgl", "JJ_j2_qgl", "H1_m", "H2_m", "H1_bb_deltaR", "H2_bb_deltaR", "JJ_m", "j1j2_deltaEta", "abs(costh_JJ_j1_cm)" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_175_325_2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_175_325_2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_175_325_2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_175_325_2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_175_325_2Node*)current->GetRight();
         else current=(BDT_175_325_2Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT_175_325_2::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128468,-0.0371532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370218,-0.0129782) , 
8, 228.049, 1, 0, 0.27555,-0.22445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796477,0.0296477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34791,-0.015209) , 
4, 149.328, 1, 0, 0.743173,0.243173) , 
8, 547.653, 1, 0, 0.490458,-0.00954237)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154889,-0.0330846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423485,-0.00700383) , 
8, 303.735, 1, 0, 0.266824,-0.221962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.805298,0.0290924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301429,-0.0191018) , 
4, 150.491, 1, 0, 0.749911,0.237726) , 
8, 543.631, 1, 0, 0.48553,-0.0138496)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348577,-0.0130158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0712023,-0.0406108) , 
4, 154.153, 1, 0, 0.276337,-0.201502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810474,0.0286255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377141,-0.0134977) , 
5, 143.93, 1, 0, 0.753203,0.229832) , 
8, 532.909, 1, 0, 0.506525,0.00670689)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342536,-0.0127566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0986866,-0.0362214) , 
4, 138.027, 1, 0, 0.259425,-0.206237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811101,0.0276989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268627,-0.0218507) , 
4, 157.947, 1, 0, 0.754843,0.224031) , 
8, 481.391, 1, 0, 0.521561,0.0214272)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384301,-0.00848257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11615,-0.0345846) , 
5, 133.815, 1, 0, 0.294181,-0.170997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.842539,0.02907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331309,-0.0162841) , 
4, 143.198, 1, 0, 0.777217,0.229675) , 
8, 601.55, 1, 0, 0.503036,0.00224556)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225649,-0.0232125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523858,0.00598129) , 
2, 0.969325, 1, 0, 0.284408,-0.172542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369943,-0.020136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.824169,0.0271402) , 
4, 83.4929, 1, 0, 0.778885,0.220382) , 
8, 601.55, 1, 0, 0.496617,-0.00391592)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14823,-0.0286672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3523,-0.00936054) , 
2, 0.93865, 1, 0, 0.193532,-0.238772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240944,-0.0279942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725972,0.0190073) , 
5, 69.3463, 1, 0, 0.672423,0.135461) , 
8, 338.878, 1, 0, 0.501017,0.00151445)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123938,-0.0312818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38718,-0.00726337) , 
10, 0.72394, 1, 0, 0.285139,-0.162245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851693,0.0272305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332951,-0.0159636) , 
4, 152.019, 1, 0, 0.79821,0.220085) , 
8, 622.235, 1, 0, 0.494333,-0.0063575)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422426,-0.00530288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129127,-0.0302161) , 
4, 136.913, 1, 0, 0.32481,-0.131958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887058,0.0297561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380342,-0.0109564) , 
4, 148.606, 1, 0, 0.830737,0.241212) , 
8, 796.695, 1, 0, 0.484247,-0.0143581)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191723,-0.024938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513934,0.00404024) , 
2, 0.969325, 1, 0, 0.261992,-0.179517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748736,0.0191524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232017,-0.021163) , 
4, 153.088, 1, 0, 0.676396,0.129446) , 
10, 0.895732, 1, 0, 0.495852,-0.00516055)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15093,-0.0255277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409052,-0.00213204) , 
2, 0.969325, 1, 0, 0.192059,-0.207712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361449,-0.0201831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733052,0.0179576) , 
4, 87.6289, 1, 0, 0.67906,0.118821) , 
8, 350.567, 1, 0, 0.504333,0.00166654)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404286,-0.00577065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0942175,-0.0310896) , 
4, 148.562, 1, 0, 0.325169,-0.116389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87551,0.026478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351879,-0.0140335) , 
4, 146.879, 1, 0, 0.81604,0.203082) , 
8, 738.045, 1, 0, 0.504722,0.000468323)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297116,-0.0117592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0937609,-0.0290498) , 
4, 134.054, 1, 0, 0.214188,-0.175848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768839,0.0179612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226537,-0.0221468) , 
4, 152.354, 1, 0, 0.698282,0.118973) , 
8, 409.917, 1, 0, 0.486448,-0.0100378)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.100428,-0.0364339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399928,-0.00551149) , 
4, 84.3184, 1, 0, 0.349961,-0.102047) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89774,0.0279958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504443,-0.0077441) , 
5, 141.451, 1, 0, 0.858193,0.222012) , 
8, 930.192, 1, 0, 0.48428,-0.0164029)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13016,-0.0251639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379236,-0.0043202) , 
8, 236.419, 1, 0, 0.266987,-0.127134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255994,-0.0312877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793438,0.0191841) , 
5, 63.8052, 1, 0, 0.754064,0.14246) , 
8, 514.988, 1, 0, 0.502355,0.00314075)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114311,-0.0274417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321256,-0.00870086) , 
2, 0.785276, 1, 0, 0.199597,-0.180213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725902,0.016018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332086,-0.0173569) , 
5, 139.918, 1, 0, 0.660684,0.0966086) , 
9, 2.726, 1, 0, 0.508687,0.00535481)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167479,-0.0237135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434435,-0.000407055) , 
2, 0.846626, 1, 0, 0.26312,-0.140328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757497,0.0173575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22817,-0.0185975) , 
4, 148.833, 1, 0, 0.671614,0.105128) , 
10, 0.871201, 1, 0, 0.513979,0.0104084)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0689875,-0.0324401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19462,-0.019029) , 
5, 84.8093, 1, 0, 0.162462,-0.203265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292198,-0.0226493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677848,0.012468) , 
4, 85.3572, 1, 0, 0.626688,0.0705121) , 
10, 0.75772, 1, 0, 0.504824,-0.00135759)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.107619,-0.0299827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324501,-0.00810253) , 
5, 84.578, 1, 0, 0.262793,-0.131775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283442,-0.0267443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77126,0.0177405) , 
5, 69.3388, 1, 0, 0.723301,0.119712) , 
9, 3.45267, 1, 0, 0.505145,0.000575226)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435951,-0.00194549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151562,-0.0268014) , 
5, 136.596, 1, 0, 0.356311,-0.0814229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913824,0.0260759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390358,-0.0110398) , 
4, 146.092, 1, 0, 0.857736,0.186045) , 
8, 910.451, 1, 0, 0.489105,-0.0105885)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253448,-0.012137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0753511,-0.0293252) , 
6, 2.0002, 1, 0, 0.194994,-0.156718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742122,0.0139292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264051,-0.0183304) , 
4, 140.954, 1, 0, 0.648005,0.0664047) , 
9, 2.81893, 1, 0, 0.497185,-0.00787892)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429091,-0.00144333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140548,-0.0254595) , 
5, 140.183, 1, 0, 0.356778,-0.066918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88573,0.0222455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316219,-0.0137792) , 
4, 157.947, 1, 0, 0.836135,0.157387) , 
8, 830.398, 1, 0, 0.506425,0.00310649)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196123,-0.0199527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495171,0.00407034) , 
2, 0.834356, 1, 0, 0.315779,-0.0903688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781211,0.0169554) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363001,-0.0122285) , 
5, 143.504, 1, 0, 0.722247,0.110109) , 
10, 0.935588, 1, 0, 0.509691,0.00527226)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375469,-0.00379007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128962,-0.0237897) , 
4, 134.352, 1, 0, 0.285709,-0.0969956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511944,-0.0138407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.840302,0.0192475) , 
5, 86.1063, 1, 0, 0.781898,0.111595) , 
8, 628.128, 1, 0, 0.490214,-0.0110247)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182906,-0.0258318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670088,0.0134868) , 
5, 72.2726, 1, 0, 0.592923,0.0618082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103033,-0.0323539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230369,-0.0172522) , 
4, 104.823, 1, 0, 0.189684,-0.192122) , 
5, 145.047, 1, 0, 0.512343,0.0110648)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172637,-0.0208324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421849,-9.71976e-05) , 
2, 0.754601, 1, 0, 0.275273,-0.105276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295634,-0.0269367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735623,0.0136187) , 
4, 83.3906, 1, 0, 0.692088,0.079864) , 
10, 0.917165, 1, 0, 0.496126,-0.00717811)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243452,-0.0151259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491402,0.00484631) , 
2, 0.785276, 1, 0, 0.344087,-0.0597746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613505,-0.0033833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.889454,0.0224042) , 
5, 85.6658, 1, 0, 0.843606,0.143399) , 
8, 790.27, 1, 0, 0.507126,0.00653994)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0589974,-0.0435797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232268,-0.023498) , 
4, 59.7453, 1, 0, 0.175387,-0.270274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676051,0.0125961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218103,-0.0170304) , 
4, 136.191, 1, 0, 0.540983,0.0333677) , 
4, 83.4445, 1, 0, 0.48965,-0.00926664)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.122926,-0.0330273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406968,-0.00736394) , 
6, 0.898346, 1, 0, 0.21029,-0.222361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692902,0.0130994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194093,-0.0181664) , 
4, 141.132, 1, 0, 0.556164,0.038885) , 
4, 85.3572, 1, 0, 0.502134,-0.00192491)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198015,-0.0189176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476468,0.00132689) , 
2, 0.809816, 1, 0, 0.313156,-0.0880931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801013,0.0168021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310418,-0.0179119) , 
5, 150.097, 1, 0, 0.741657,0.100868) , 
10, 0.941651, 1, 0, 0.500726,-0.00537817)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0625254,-0.0318719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329854,-0.00719928) , 
5, 67.1221, 1, 0, 0.291046,-0.0916094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334434,-0.0226737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78233,0.0160321) , 
4, 81.6241, 1, 0, 0.738884,0.0979018) , 
10, 0.935526, 1, 0, 0.496603,-0.00462375)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220314,-0.0232334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669057,0.0106089) , 
4, 91.1366, 1, 0, 0.567132,0.0231116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.067879,-0.0305775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171871,-0.0179333) , 
5, 86.797, 1, 0, 0.143794,-0.176856) , 
4, 146.092, 1, 0, 0.47494,-0.0204363)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266238,-0.0189317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721188,0.0151797) , 
5, 83.9587, 1, 0, 0.595967,0.0472623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115918,-0.0237566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608607,0.0016233) , 
8, 663.369, 1, 0, 0.22423,-0.148715) , 
5, 135.961, 1, 0, 0.502853,-0.00182666)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102518,-0.0301909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387838,-0.00902594) , 
5, 61.1439, 1, 0, 0.278654,-0.144857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695125,0.0131073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196854,-0.0198642) , 
5, 141.904, 1, 0, 0.561783,0.0348271) , 
5, 88.3509, 1, 0, 0.48861,-0.0116114)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141423,-0.026651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631696,-0.00419299) , 
8, 1028.26, 1, 0, 0.214721,-0.195707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655347,0.00845119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141614,-0.0191957) , 
4, 149.763, 1, 0, 0.540127,0.0202864) , 
4, 89.2009, 1, 0, 0.483166,-0.0175228)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235756,-0.0121353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521928,0.0113351) , 
2, 0.98773, 1, 0, 0.269219,-0.0776547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24021,-0.0307282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821694,0.0155581) , 
5, 63.6977, 1, 0, 0.776471,0.0895477) , 
8, 547.155, 1, 0, 0.500734,-0.00134174)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168632,-0.0218463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413139,-0.00137498) , 
2, 0.417178, 1, 0, 0.31625,-0.077278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89072,0.0197084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443272,-0.0137712) , 
5, 145.041, 1, 0, 0.847141,0.114263) , 
8, 798.437, 1, 0, 0.483453,-0.0169526)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0877412,-0.0328128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192069,-0.0171334) , 
4, 114.519, 1, 0, 0.134091,-0.213694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655144,0.00879037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240475,-0.0156131) , 
5, 137.641, 1, 0, 0.546492,0.0194426) , 
5, 70.9251, 1, 0, 0.489971,-0.0125097)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0475828,-0.0271335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201046,-0.0113308) , 
5, 80.8284, 1, 0, 0.161287,-0.116234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2904,-0.019681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697453,0.0102991) , 
4, 85.8173, 1, 0, 0.645658,0.049834) , 
8, 297.892, 1, 0, 0.499825,-0.000165087)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27838,-0.0159132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711055,0.0129499) , 
4, 92.6642, 1, 0, 0.600316,0.0417798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194507,-0.0297456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345309,-0.00847711) , 
3, 0.147239, 1, 0, 0.308662,-0.110886) , 
6, 1.71668, 1, 0, 0.501909,-0.00973136)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0751869,-0.0250356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231479,-0.035447) , 
8, 658.836, 1, 0, 0.126389,-0.234024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648106,0.00748477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14834,-0.0173748) , 
4, 149.615, 1, 0, 0.534426,0.0164688) , 
4, 74.8219, 1, 0, 0.49247,-0.00928819)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163878,-0.0170329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311804,4.42471e-05) , 
1, 45.5828, 1, 0, 0.208934,-0.0912684) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715753,0.0109781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210172,-0.0199448) , 
5, 155.965, 1, 0, 0.647398,0.0523937) , 
10, 0.828272, 1, 0, 0.503956,0.00539521)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274402,-0.0150945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6932,0.0113714) , 
5, 83.9261, 1, 0, 0.59272,0.0390143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0803089,-0.0237633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458145,-0.00777627) , 
8, 611.735, 1, 0, 0.183754,-0.142411) , 
5, 144.264, 1, 0, 0.5112,0.00285044)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422876,-0.000173876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187437,-0.0166651) , 
5, 129.789, 1, 0, 0.343579,-0.0439669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549868,-0.00918012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.884174,0.0183356) , 
4, 88.1279, 1, 0, 0.847842,0.100219) , 
8, 795.95, 1, 0, 0.512264,0.00426613)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137287,-0.0258766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642074,0.00829773) , 
4, 76.0078, 1, 0, 0.572712,0.0276752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.16481,-0.019694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616036,0.00140129) , 
9, 4.27125, 1, 0, 0.26141,-0.11745) , 
6, 1.8915, 1, 0, 0.490307,-0.0107409)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302913,-0.0126016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67976,0.010264) , 
5, 87.1781, 1, 0, 0.573476,0.0285507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162659,-0.02098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317645,0.00331785) , 
5, 266.796, 1, 0, 0.185557,-0.13319) , 
5, 144.799, 1, 0, 0.49257,-0.00518278)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180706,-0.0201276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674925,-0.000662162) , 
8, 782.17, 1, 0, 0.316221,-0.11859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727701,0.0140269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304609,-0.00891046) , 
5, 129.61, 1, 0, 0.571899,0.0428419) , 
5, 92.6792, 1, 0, 0.500208,-0.00242254)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206068,-0.0193851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487499,0.00761458) , 
1, 57.4893, 1, 0, 0.241604,-0.119512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658597,0.00936481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179093,-0.0129322) , 
4, 153.399, 1, 0, 0.574581,0.0421275) , 
2, 0.147239, 1, 0, 0.507282,0.00945818)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222991,-0.0188677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345846,-0.0020937) , 
0, 46.5647, 1, 0, 0.313062,-0.0529988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736629,0.00093593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876153,0.0187436) , 
0, 54.888, 1, 0, 0.831127,0.0867943) , 
8, 740.1, 1, 0, 0.494027,-0.00416776)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14018,-0.0155319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405433,0.00748546) , 
2, 0.98773, 1, 0, 0.164028,-0.0949501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732113,0.00901065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205323,-0.0134486) , 
4, 152.563, 1, 0, 0.653429,0.0412482) , 
8, 297.973, 1, 0, 0.500512,-0.00130802)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116491,-0.0197251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295477,-0.000124204) , 
3, 0.766871, 1, 0, 0.16811,-0.101041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716417,0.00905881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253663,-0.0119834) , 
4, 141.16, 1, 0, 0.616046,0.0329561) , 
9, 2.3386, 1, 0, 0.494197,-0.00349431)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202504,-0.0266697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455279,-0.00482818) , 
3, 0.147239, 1, 0, 0.392901,-0.0798686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696671,0.0120864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291586,-0.00929817) , 
5, 133.639, 1, 0, 0.578069,0.0431036) , 
0, 52.048, 1, 0, 0.514241,0.000714598)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183454,-0.0196965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412848,-0.00117677) , 
4, 94.0834, 1, 0, 0.363115,-0.0401585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677658,-0.00728601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.89981,0.0188888) , 
0, 44.653, 1, 0, 0.875374,0.0975924) , 
8, 933.045, 1, 0, 0.494681,-0.00477919)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123785,-0.0262579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266062,-0.0114464) , 
7, 1.03255, 1, 0, 0.166204,-0.159581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669311,0.00927261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260279,-0.0103178) , 
5, 133.47, 1, 0, 0.547313,0.0264218) , 
5, 70.9251, 1, 0, 0.500287,0.00347016)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307897,-0.0154633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620426,0.0140726) , 
1, 64.6672, 1, 0, 0.342911,-0.0905787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193138,-0.0182652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647181,0.0106317) , 
5, 70.8228, 1, 0, 0.588943,0.0511861) , 
2, 0.392638, 1, 0, 0.506459,0.00365853)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103437,-0.0319333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214226,-0.0123582) , 
7, 2.2905, 1, 0, 0.140739,-0.198584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639734,0.00604535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154663,-0.0147255) , 
4, 150.799, 1, 0, 0.540199,0.0147001) , 
4, 75.594, 1, 0, 0.504881,-0.00415702)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201405,-0.0233565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477511,-0.00410108) , 
5, 90.7855, 1, 0, 0.389546,-0.0776919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770704,0.0183373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350988,-0.00609421) , 
6, 1.60955, 1, 0, 0.566282,0.0457046) , 
4, 104.782, 1, 0, 0.50994,0.00636711)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191213,-0.0185459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794322,0.00598214) , 
8, 1098.41, 1, 0, 0.27572,-0.107881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224658,-0.00748266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721704,0.00926133) , 
8, 352.335, 1, 0, 0.5549,0.0261922) , 
2, 0.171779, 1, 0, 0.502393,0.000976015)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0955718,-0.0283853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200612,-0.012742) , 
3, 0.533742, 1, 0, 0.136818,-0.151702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673005,0.00809756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248694,-0.0114761) , 
5, 133.043, 1, 0, 0.548118,0.0174912) , 
5, 67.2558, 1, 0, 0.502445,-0.0012971)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273864,-0.0172713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777241,0.0110372) , 
10, 0.978227, 1, 0, 0.371715,-0.0888564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765801,0.0148724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254778,-0.0100277) , 
4, 133.413, 1, 0, 0.541026,0.0272278) , 
4, 104.942, 1, 0, 0.489426,-0.00815033)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0855816,-0.0169435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220526,-0.0223017) , 
9, 3.05793, 1, 0, 0.154432,-0.14016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652734,0.00960623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377134,-0.00953347) , 
7, 2.62247, 1, 0, 0.569309,0.0266096) , 
5, 71.2689, 1, 0, 0.509383,0.00252101)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0798454,-0.0257566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241622,-0.0089029) , 
7, 0.993442, 1, 0, 0.136955,-0.132546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677354,0.00793382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247868,-0.0117988) , 
5, 134.072, 1, 0, 0.545478,0.014885) , 
5, 71.4915, 1, 0, 0.492482,-0.0042407)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162591,-0.0211591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673794,0.00903067) , 
4, 76.5089, 1, 0, 0.609857,0.0378882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.135384,-0.0186206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323597,-0.00426481) , 
2, 0.78484, 1, 0, 0.198583,-0.0910157) , 
4, 138.454, 1, 0, 0.507281,0.00573806)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29929,-0.0214985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431302,-0.00477055) , 
0, 41.9924, 1, 0, 0.394101,-0.0688881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325293,-0.0123648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649717,0.0106352) , 
2, 0.208589, 1, 0, 0.576694,0.0381348) , 
1, 35.967, 1, 0, 0.503722,-0.00463633)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378912,-0.0100513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12181,-0.0297223) , 
5, 131.09, 1, 0, 0.328408,-0.0993245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175176,-0.0189064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584766,0.00556384) , 
4, 85.3572, 1, 0, 0.531388,0.0160276) , 
0, 48.1909, 1, 0, 0.479801,-0.0132887)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0632513,-0.0300184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190217,-0.0151098) , 
6, 0.647748, 1, 0, 0.140353,-0.14287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694372,0.00989394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35619,-0.00787567) , 
6, 1.54583, 1, 0, 0.532431,0.00846756) , 
4, 79.571, 1, 0, 0.483095,-0.0105756)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413013,-0.00593243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0825222,-0.0310014) , 
6, 2.88835, 1, 0, 0.375679,-0.0631167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246116,-0.0127565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634771,0.00971225) , 
5, 80.2754, 1, 0, 0.572096,0.0414765) , 
1, 34.0184, 1, 0, 0.504969,0.00573057)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408965,-0.0088685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235765,-0.0247689) , 
7, 2.19959, 1, 0, 0.33177,-0.114252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275609,-0.00470748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719059,0.0107628) , 
10, 0.864999, 1, 0, 0.558873,0.0353577) , 
3, 0.171779, 1, 0, 0.498997,-0.00408731)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0906675,-0.0141263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175061,-0.0267514) , 
8, 448.36, 1, 0, 0.137936,-0.15885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672956,0.00743113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185026,-0.0114157) , 
4, 141.183, 1, 0, 0.550518,0.020703) , 
4, 73.9398, 1, 0, 0.511304,0.00363713)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323737,-0.0109824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.745802,0.0109116) , 
4, 97.7483, 1, 0, 0.606973,0.0253475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188899,-0.0157375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373732,0.00503428) , 
0, 84.6991, 1, 0, 0.228169,-0.0772309) , 
4, 134.417, 1, 0, 0.48522,-0.00762253)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103431,-0.024065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330713,-0.00266385) , 
6, 0.910574, 1, 0, 0.180504,-0.109337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630007,0.00793301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369378,-0.00999438) , 
7, 2.8188, 1, 0, 0.577817,0.0285085) , 
4, 85.1956, 1, 0, 0.517642,0.00763129)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31165,-0.0112082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476374,0.00427691) , 
3, 0.760736, 1, 0, 0.361842,-0.0471158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.931877,0.0215112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.824417,0.00704119) , 
7, 1.81131, 1, 0, 0.880238,0.0777032) , 
8, 1026.29, 1, 0, 0.490546,-0.0161265)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314313,-0.0120752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482046,0.00342392) , 
1, 37.046, 1, 0, 0.404601,-0.0274185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678806,-0.000462355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874927,0.0199242) , 
5, 92.0055, 1, 0, 0.833018,0.0866565) , 
10, 0.981591, 1, 0, 0.498823,-0.00232991)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242693,-0.0134415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.768218,0.00888353) , 
10, 0.978423, 1, 0, 0.36723,-0.0550243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674016,0.00873286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16273,-0.0115483) , 
4, 161.087, 1, 0, 0.59979,0.0407283) , 
2, 0.503067, 1, 0, 0.506449,0.00229652)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.152336,-0.0170245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652774,0.0064502) , 
5, 67.5786, 1, 0, 0.576192,0.021543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136338,-0.0189861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252279,-0.00164848) , 
5, 199.844, 1, 0, 0.174997,-0.082206) , 
5, 144.618, 1, 0, 0.493746,0.000222457)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302638,-0.0177892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55397,0.00497811) , 
2, 0.95092, 1, 0, 0.356777,-0.0898609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662514,0.00732316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243951,-0.00798136) , 
4, 137.07, 1, 0, 0.551825,0.0216653) , 
0, 48.9144, 1, 0, 0.50047,-0.00769905)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185954,-0.0267197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437152,-0.00417628) , 
3, 0.128834, 1, 0, 0.367927,-0.0725942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150941,-0.0114324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684388,0.0080778) , 
8, 263.324, 1, 0, 0.551234,0.0222389) , 
0, 48.8587, 1, 0, 0.501553,-0.00346324)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243714,-0.0107526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763319,0.0056824) , 
9, 4.32586, 1, 0, 0.419403,-0.0356786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703673,0.0108985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355272,-0.00624141) , 
5, 132.09, 1, 0, 0.630317,0.0501738) , 
2, 0.828221, 1, 0, 0.504347,-0.00110218)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223142,-0.0171025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380255,-0.00128334) , 
0, 83.5525, 1, 0, 0.259193,-0.0842813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222148,-0.0128514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613503,0.00571922) , 
4, 85.1956, 1, 0, 0.560033,0.0211386) , 
2, 0.153374, 1, 0, 0.503996,0.00150185)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361856,-0.00215941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223144,-0.0313853) , 
7, 2.29554, 1, 0, 0.277065,-0.1444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247317,-0.0124562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590427,0.00550134) , 
5, 79.2645, 1, 0, 0.534743,0.0170898) , 
0, 40.5389, 1, 0, 0.505421,-0.00128675)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190992,-0.0186462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42072,-0.00146744) , 
2, 0.91411, 1, 0, 0.255522,-0.0893721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701004,0.00947527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385527,-0.00625735) , 
7, 2.43695, 1, 0, 0.571269,0.0183841) , 
5, 83.9109, 1, 0, 0.508423,-0.00306338)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223567,-0.0233626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446318,-0.00389437) , 
0, 54.0974, 1, 0, 0.34384,-0.0878656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609381,0.00498543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171592,-0.0147005) , 
5, 157.224, 1, 0, 0.545191,0.0141416) , 
3, 0.177914, 1, 0, 0.493241,-0.0121768)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1165,-0.0160352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42778,0.00886828) , 
2, 0.98773, 1, 0, 0.149138,-0.076638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718304,0.00711183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184577,-0.0110369) , 
4, 152.956, 1, 0, 0.634634,0.027673) , 
8, 275.642, 1, 0, 0.499642,-0.0013308)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230421,-0.00885049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471489,0.0089159) , 
2, 0.97546, 1, 0, 0.274546,-0.035456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617542,-0.00907815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822116,0.0121184) , 
3, 0.165644, 1, 0, 0.781128,0.0453704) , 
8, 564.33, 1, 0, 0.503039,0.00100067)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353615,-0.00736982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521892,0.0076741) , 
3, 0.846626, 1, 0, 0.393723,-0.0255205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650739,-0.00607693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.838323,0.0158275) , 
7, 1.04871, 1, 0, 0.809029,0.069156) , 
10, 0.975457, 1, 0, 0.507522,0.000422186)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0939765,-0.0225326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660462,0.00710188) , 
5, 60.5649, 1, 0, 0.589803,0.0249357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215042,-0.0195458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236174,-0.00437376) , 
4, 120.148, 1, 0, 0.226476,-0.0734596) , 
5, 135.854, 1, 0, 0.500669,0.000796611)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206038,-0.0116001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38232,0.00837384) , 
0, 91.2115, 1, 0, 0.232206,-0.0554508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233709,-0.0162406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718243,0.00740549) , 
5, 69.3388, 1, 0, 0.668727,0.0302926) , 
10, 0.871201, 1, 0, 0.496838,-0.00347063)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0588167,-0.0258971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121999,-0.0129509) , 
3, 0.116564, 1, 0, 0.102144,-0.0969915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145374,-0.0212429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605695,0.00257454) , 
5, 61.0284, 1, 0, 0.569086,0.0043923) , 
8, 185.184, 1, 0, 0.494978,-0.0116981)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160156,-0.0154324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213426,-0.0285942) , 
1, 47.9626, 1, 0, 0.174168,-0.116282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414418,-0.00655586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594213,0.00509179) , 
1, 37.8834, 1, 0, 0.51886,-4.8634e-05) , 
2, 0.0552147, 1, 0, 0.482714,-0.0122374)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223127,-0.00767256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138067,-0.0238129) , 
1, 41.1606, 1, 0, 0.189647,-0.0924179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685144,0.00795742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141874,-0.0118314) , 
4, 151.869, 1, 0, 0.555034,0.0229286) , 
4, 85.0105, 1, 0, 0.503121,0.00654054)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14442,-0.025419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319438,-0.00724547) , 
3, 0.306748, 1, 0, 0.252684,-0.0899801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64751,0.005698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139515,-0.0131716) , 
4, 153.182, 1, 0, 0.553813,0.015016) , 
2, 0.134969, 1, 0, 0.50088,-0.00344026)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105051,-0.0124384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255283,-0.0190486) , 
9, 3.04997, 1, 0, 0.181689,-0.103083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692608,0.00753943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276482,-0.0087258) , 
5, 129.607, 1, 0, 0.55169,0.0137754) , 
5, 75.7073, 1, 0, 0.497539,-0.00332719)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0530828,-0.025797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191836,-0.00770633) , 
5, 89.9802, 1, 0, 0.150286,-0.0742004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183989,-0.0164938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643466,0.00522225) , 
4, 74.5675, 1, 0, 0.608613,0.0222353) , 
10, 0.693361, 1, 0, 0.508371,0.00114358)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635071,0.00594596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127587,-0.0162482) , 
4, 157.191, 1, 0, 0.566197,0.0191021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144413,-0.00558668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218074,-0.0228033) , 
9, 3.80486, 1, 0, 0.171753,-0.0853376) , 
5, 152.904, 1, 0, 0.503603,0.00252848)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261107,-0.00790854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609002,0.0120719) , 
2, 0.993865, 1, 0, 0.297151,-0.0356021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639149,-0.00170156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774862,0.0129018) , 
0, 55.8372, 1, 0, 0.724589,0.0405284) , 
10, 0.926417, 1, 0, 0.502555,0.000982095)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424517,-0.00315823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230719,-0.0174307) , 
7, 2.16988, 1, 0, 0.341322,-0.058122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639066,0.00654706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184917,-0.0116208) , 
5, 148.84, 1, 0, 0.566015,0.0239556) , 
2, 0.355828, 1, 0, 0.498385,-0.000748926)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218424,-0.0212122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432427,-0.00286814) , 
3, 0.177914, 1, 0, 0.369976,-0.0528261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661805,0.00713385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210077,-0.00823336) , 
5, 147.369, 1, 0, 0.564753,0.02329) , 
0, 51.5851, 1, 0, 0.499732,-0.00211931)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240806,-0.00737466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466297,0.00547565) , 
2, 0.969325, 1, 0, 0.286649,-0.028719) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386571,-0.0149696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.838059,0.0113054) , 
4, 80.8885, 1, 0, 0.807869,0.0470732) , 
8, 602.933, 1, 0, 0.513837,0.00431715)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234661,-0.0103987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282858,-0.0230086) , 
2, 0.981595, 1, 0, 0.244279,-0.0867571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728148,0.00819472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296426,-0.00898433) , 
4, 130.332, 1, 0, 0.556023,0.0087791) , 
4, 90.4742, 1, 0, 0.503475,-0.00732478)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148095,-0.0119763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398638,-0.0206813) , 
9, 4.1563, 1, 0, 0.226332,-0.0961742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717666,0.00748471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258154,-0.00641768) , 
4, 135.119, 1, 0, 0.566471,0.018334) , 
4, 91.4378, 1, 0, 0.500291,-0.00394563)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339485,-0.00703452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734819,0.0105928) , 
5, 91.8261, 1, 0, 0.585288,0.0233888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275189,-0.012044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.89668,0.019423) , 
8, 1489.64, 1, 0, 0.326547,-0.0592204) , 
5, 124.069, 1, 0, 0.4926,-0.00620388)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358211,-0.00751665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.834202,0.0133007) , 
10, 0.987677, 1, 0, 0.438192,-0.0275661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67023,0.00992592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135221,-0.0107657) , 
4, 158.147, 1, 0, 0.578541,0.041768) , 
3, 0.650307, 1, 0, 0.49197,-0.000999004)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294704,-0.0147452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462322,0.00356745) , 
3, 0.730061, 1, 0, 0.342433,-0.0553302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679113,0.00737563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138168,-0.0116347) , 
4, 157.465, 1, 0, 0.594925,0.0285606) , 
2, 0.490798, 1, 0, 0.494254,-0.00488755)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311122,-0.0115293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.840122,0.0148112) , 
10, 0.984237, 1, 0, 0.392353,-0.0507651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774278,0.0129793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397868,-0.00221916) , 
6, 1.42834, 1, 0, 0.560242,0.0248748) , 
4, 104.599, 1, 0, 0.506581,0.000698529)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0906103,-0.0272221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329608,-0.00744259) , 
4, 93.9722, 1, 0, 0.264882,-0.0749943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407732,-0.0119336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595055,0.00528671) , 
3, 0.110429, 1, 0, 0.565006,0.0144677) , 
2, 0.171779, 1, 0, 0.498933,-0.00522768)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290624,-0.0088088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700983,0.00680099) , 
5, 88.3611, 1, 0, 0.564116,0.00962668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321331,-0.0142204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177672,0.00544805) , 
4, 151.242, 1, 0, 0.27644,-0.0584833) , 
5, 131.525, 1, 0, 0.488018,-0.00839032)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134126,-0.0221791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339936,-0.00307156) , 
4, 106.084, 1, 0, 0.25155,-0.0702915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634471,0.00670047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271205,-0.012189) , 
7, 3.02627, 1, 0, 0.574209,0.0206038) , 
5, 84.2796, 1, 0, 0.506422,0.00150765)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323278,-0.00653194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643601,0.00489723) , 
4, 96.0392, 1, 0, 0.557909,0.0106162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.124628,-0.0259299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199228,-0.00701702) , 
0, 48.9144, 1, 0, 0.167763,-0.0895216) , 
6, 2.4197, 1, 0, 0.502789,-0.0035313)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128143,-0.0121821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453457,0.00781495) , 
2, 0.981595, 1, 0, 0.162189,-0.0521316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.157813,-0.0207093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681415,0.00476386) , 
5, 58.5111, 1, 0, 0.650051,0.0191892) , 
8, 292.648, 1, 0, 0.505383,-0.00195998)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359116,-0.0107823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.907255,0.0192372) , 
9, 5.62318, 1, 0, 0.424985,-0.054147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76236,0.0105804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291376,-0.00445007) , 
4, 131.73, 1, 0, 0.531288,0.0193106) , 
4, 108.731, 1, 0, 0.491548,-0.00815078)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102417,-0.0241292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186545,-0.0036603) , 
7, 2.05864, 1, 0, 0.138406,-0.0837197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645542,0.00577564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24736,-0.0089398) , 
5, 135.854, 1, 0, 0.5415,0.0116609) , 
4, 81.6677, 1, 0, 0.492317,2.32581e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165504,-0.0152993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649559,-0.000534081) , 
8, 802.239, 1, 0, 0.285,-0.0700757) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602725,0.00620308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10503,-0.0217023) , 
6, 2.93308, 1, 0, 0.575041,0.026846) , 
5, 88.2144, 1, 0, 0.504496,0.00327232)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378201,-0.0119875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638019,0.00778502) , 
1, 27.9429, 1, 0, 0.601684,0.0274845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276681,-0.0134284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437578,0.00497419) , 
3, 0.705521, 1, 0, 0.326551,-0.046024) , 
5, 127.305, 1, 0, 0.51851,0.00526235)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400281,0.000601158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259162,-0.0219865) , 
6, 1.58224, 1, 0, 0.31132,-0.084792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210031,-0.01125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589788,0.00328155) , 
5, 77.6106, 1, 0, 0.53217,0.00655408) , 
0, 43.8782, 1, 0, 0.494367,-0.00908193)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246897,-0.0119781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762634,0.00546873) , 
9, 4.51859, 1, 0, 0.360237,-0.0524554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680475,0.0072004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303688,-0.006738) , 
5, 131.813, 1, 0, 0.570216,0.0162725) , 
1, 37.1856, 1, 0, 0.474375,-0.015097)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240901,-0.00993258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261738,-0.0241817) , 
2, 0.92591, 1, 0, 0.247767,-0.0955272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283383,-0.00945726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590659,0.00451474) , 
5, 85.4824, 1, 0, 0.529121,0.0101713) , 
0, 39.9262, 1, 0, 0.501161,-0.000332449)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255506,-0.00399113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233532,-0.0158776) , 
1, 37.2009, 1, 0, 0.244221,-0.0602676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719896,0.00750923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351331,-0.00687177) , 
5, 125.713, 1, 0, 0.566885,0.00883034) , 
5, 83.6386, 1, 0, 0.497462,-0.00603647)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38945,0.0054972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246657,-0.0274452) , 
6, 1.56453, 1, 0, 0.295209,-0.109256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18069,-0.00744709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65306,0.0075312) , 
10, 0.720958, 1, 0, 0.53611,0.02276) , 
0, 41.5819, 1, 0, 0.505073,0.00575173)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447056,-0.00162106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167019,-0.0208299) , 
7, 3.19155, 1, 0, 0.425936,-0.0188823) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828201,0.00405532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.892649,0.0194074) , 
6, 1.08222, 1, 0, 0.871471,0.0655015) , 
10, 0.987617, 1, 0, 0.493851,-0.00601928)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256791,-0.0053208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126654,-0.023444) , 
7, 1.69988, 1, 0, 0.176943,-0.0907118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.111706,-0.0211825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564323,0.00286087) , 
4, 63.6679, 1, 0, 0.533972,0.0076041) , 
2, 0.0674847, 1, 0, 0.487626,-0.00515832)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.138748,-0.0126601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497847,0.00590748) , 
8, 466.981, 1, 0, 0.183485,-0.0549163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419902,-0.00815945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659624,0.00611681) , 
2, 0.171779, 1, 0, 0.620537,0.0214611) , 
10, 0.742387, 1, 0, 0.510258,0.00218902)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.170831,-0.0245345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405545,-0.0031808) , 
2, 0.864852, 1, 0, 0.247906,-0.111419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471549,-0.0013677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66872,0.0100339) , 
2, 0.969325, 1, 0, 0.510422,0.00626619) , 
0, 38.2511, 1, 0, 0.490368,-0.00272427)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0980529,-0.022198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135751,-0.00799297) , 
6, 1.13559, 1, 0, 0.123156,-0.06638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466706,-0.00726537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669189,0.00511105) , 
0, 52.0759, 1, 0, 0.601165,0.00295092) , 
8, 234.73, 1, 0, 0.482657,-0.0142375)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641947,0.00735315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138659,-0.0198287) , 
6, 2.10059, 1, 0, 0.569833,0.0194836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586634,0.00166086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255534,-0.012992) , 
5, 124.875, 1, 0, 0.401442,-0.0376394) , 
7, 2.08118, 1, 0, 0.491282,-0.00716311)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444315,-0.00533522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583177,0.00540276) , 
3, 0.257669, 1, 0, 0.537383,0.00997894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209477,-0.0198263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375581,0.0128951) , 
0, 66.7109, 1, 0, 0.242241,-0.0797362) , 
7, 3.063, 1, 0, 0.498243,-0.00191856)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227139,-0.021892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43273,-0.00434918) , 
0, 47.5581, 1, 0, 0.379913,-0.0529027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596407,0.005028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179662,-0.0100341) , 
5, 166.728, 1, 0, 0.543,0.0175001) , 
3, 0.184049, 1, 0, 0.502699,0.000102525)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225453,-0.0130754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772764,0.0125109) , 
8, 1386.68, 1, 0, 0.284774,-0.0605163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714231,0.00619065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336454,-0.00578582) , 
5, 125.167, 1, 0, 0.546853,0.00550044) , 
5, 88.103, 1, 0, 0.4864,-0.00972745)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0825367,-0.0187418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18148,-0.00558622) , 
8, 139.58, 1, 0, 0.150941,-0.0496037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543013,-0.00300851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685206,0.00753327) , 
3, 0.484663, 1, 0, 0.615009,0.0131789) , 
8, 261.099, 1, 0, 0.500035,-0.00237571)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123911,-0.0254292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386288,-0.00501293) , 
3, 0.122699, 1, 0, 0.329447,-0.0522467) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664411,0.00783851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31092,-0.0052871) , 
4, 131.75, 1, 0, 0.547495,0.019301) , 
1, 31.4417, 1, 0, 0.492272,0.0011808)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234691,-0.00953433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717113,0.00723891) , 
4, 90.189, 1, 0, 0.59484,0.0168896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117936,-0.0209231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282956,-0.00324548) , 
0, 52.583, 1, 0, 0.227802,-0.0504585) , 
4, 134.352, 1, 0, 0.485257,-0.00321782)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310731,-0.00623646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462575,0.00857665) , 
0, 91.1269, 1, 0, 0.331742,-0.0250216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658184,-0.00710145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.767601,0.00824078) , 
6, 0.898902, 1, 0, 0.749485,0.0290939) , 
10, 0.953903, 1, 0, 0.496864,-0.00363118)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194893,-0.0113162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667418,0.00316244) , 
10, 0.941758, 1, 0, 0.395302,-0.0278536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717217,0.0104196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247126,-0.00493566) , 
4, 139.199, 1, 0, 0.616829,0.0407961) , 
2, 0.650307, 1, 0, 0.50963,0.0075757)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327283,-0.0103265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657575,0.00684068) , 
2, 0.177914, 1, 0, 0.593456,0.0191417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246537,-0.01622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39024,0.00307428) , 
0, 70.1817, 1, 0, 0.310959,-0.0431774) , 
5, 127.74, 1, 0, 0.50284,-0.000848294)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40677,-0.00455672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628373,0.00924198) , 
2, 0.993865, 1, 0, 0.428153,-0.0177376) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786736,0.00104137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955343,0.0223184) , 
1, 33.7699, 1, 0, 0.918501,0.063109) , 
8, 1503.66, 1, 0, 0.488704,-0.00775427)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.140693,-0.00496533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0404592,-0.0256988) , 
7, 2.46395, 1, 0, 0.0961797,-0.0602634) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603471,0.00424477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33483,-0.00906529) , 
7, 3.04933, 1, 0, 0.571531,0.0141536) , 
8, 176.811, 1, 0, 0.500947,0.00310369)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361541,-0.00703062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927926,0.0192472) , 
8, 1373.8, 1, 0, 0.434627,-0.0255622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691138,0.0107553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157592,-0.00326378) , 
4, 166.309, 1, 0, 0.610964,0.0498827) , 
3, 0.644172, 1, 0, 0.497896,0.00150694)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0879718,-0.0246289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191725,-0.000772876) , 
7, 2.26371, 1, 0, 0.126793,-0.0806432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696968,0.0075248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453648,-0.00258249) , 
6, 1.26616, 1, 0, 0.546363,0.00595749) , 
4, 75.594, 1, 0, 0.506964,-0.00217469)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218501,-0.00662069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463325,-0.0216201) , 
9, 4.46583, 1, 0, 0.288833,-0.066493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72621,0.00738609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323711,-0.0071105) , 
5, 125.187, 1, 0, 0.546673,0.00412325) , 
5, 88.2144, 1, 0, 0.487536,-0.0120731)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102808,-0.0178742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116795,-0.00495784) , 
6, 1.56137, 1, 0, 0.108705,-0.0607097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357023,-0.0117343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598035,0.00402228) , 
0, 39.1054, 1, 0, 0.576751,0.014223) , 
8, 186.693, 1, 0, 0.500368,0.00199426)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268921,0.0032719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263336,-0.0128905) , 
0, 43.0465, 1, 0, 0.264481,-0.0529437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713651,0.00535342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239276,-0.00728646) , 
5, 133.539, 1, 0, 0.556589,0.00650731) , 
5, 88.2395, 1, 0, 0.484449,-0.00817496)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15129,-0.00505356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211398,-0.0162138) , 
9, 2.70254, 1, 0, 0.165235,-0.0437409) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130888,-0.0200028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666553,0.00489129) , 
4, 64.8607, 1, 0, 0.642108,0.0202789) , 
8, 281.565, 1, 0, 0.507455,0.00220188)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0815304,-0.0162333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550707,-0.000544966) , 
8, 235.558, 1, 0, 0.425764,-0.0203342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455853,-0.00398528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704354,0.0129607) , 
3, 0.349693, 1, 0, 0.610478,0.0362016) , 
2, 0.846626, 1, 0, 0.498452,0.00191353)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129512,-0.0139698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583614,0.00205955) , 
5, 61.1306, 1, 0, 0.54058,0.00383843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131567,-0.0235667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171526,-0.00707993) , 
0, 43.6254, 1, 0, 0.158637,-0.0686601) , 
6, 2.3902, 1, 0, 0.481963,-0.00728806)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225653,-0.00766732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735672,0.00501451) , 
9, 4.13317, 1, 0, 0.415512,-0.0164619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273324,-0.00588898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673947,0.00769692) , 
10, 0.674747, 1, 0, 0.611354,0.0319982) , 
2, 0.809816, 1, 0, 0.497407,0.00380246)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275333,-0.00111745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219251,-0.0297085) , 
7, 2.13951, 1, 0, 0.240021,-0.125133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0754211,-0.0197494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559713,0.00184204) , 
8, 138.198, 1, 0, 0.513148,0.00123437) , 
0, 39.9047, 1, 0, 0.486068,-0.0112948)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501409,-0.000479383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173886,-0.0170682) , 
7, 3.11991, 1, 0, 0.468451,-0.0110717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174295,-0.00143077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757732,0.0154633) , 
8, 228.653, 1, 0, 0.629782,0.064621) , 
3, 0.907975, 1, 0, 0.496339,0.00201258)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2258,-0.0109172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462626,-0.00148402) , 
5, 89.02, 1, 0, 0.404575,-0.0212554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742285,-0.00330271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.83831,0.0131974) , 
0, 52.2044, 1, 0, 0.814752,0.0383837) , 
10, 0.981591, 1, 0, 0.492156,-0.00852123)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0898283,-0.0192164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486634,7.52393e-05) , 
5, 66.5965, 1, 0, 0.440273,-0.00931674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880589,0.00862816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953977,0.0222747) , 
8, 1688.63, 1, 0, 0.934948,0.0660099) , 
8, 1469.92, 1, 0, 0.496976,-0.000682329)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332114,-0.0103236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52167,0.0150047) , 
0, 86.1377, 1, 0, 0.370524,-0.0303371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623345,0.00615285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322469,-0.0084356) , 
7, 3.02362, 1, 0, 0.58496,0.0228318) , 
2, 0.355828, 1, 0, 0.522328,0.00730236)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12355,-0.00894511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112177,-0.0267786) , 
1, 44.9601, 1, 0, 0.120251,-0.0736131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478783,-0.00244308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67343,0.00805599) , 
2, 0.828221, 1, 0, 0.561309,0.0127167) , 
5, 66.7098, 1, 0, 0.510641,0.00279926)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219107,-0.0176297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476381,0.000213448) , 
0, 47.9493, 1, 0, 0.404642,-0.0247291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282744,-0.00671175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634597,0.00723357) , 
4, 90.8727, 1, 0, 0.56816,0.0242101) , 
3, 0.245399, 1, 0, 0.516679,0.00880223)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322324,0.000559869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129684,-0.0129243) , 
6, 1.61419, 1, 0, 0.234728,-0.0276656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199496,-0.0174174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739411,0.00785335) , 
4, 74.5675, 1, 0, 0.696749,0.027974) , 
10, 0.880388, 1, 0, 0.508742,0.00533304)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132314,-0.0104756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655864,0.00378757) , 
8, 181.606, 1, 0, 0.580501,0.0100539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141659,-0.00334807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280841,-0.0167876) , 
9, 3.83576, 1, 0, 0.185314,-0.0488023) , 
5, 144.511, 1, 0, 0.504337,-0.00128932)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299477,-0.0169467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545527,0.0019876) , 
6, 1.05295, 1, 0, 0.435998,-0.0332245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864635,0.0214661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471735,0.000700534) , 
6, 0.904563, 1, 0, 0.524385,0.0166981) , 
4, 110.12, 1, 0, 0.490684,-0.00233661)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482914,-0.00244777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789527,0.0127035) , 
4, 111.623, 1, 0, 0.610916,0.0187654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235784,-0.0122017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39647,0.00636386) , 
0, 83.1315, 1, 0, 0.275957,-0.038828) , 
4, 130.986, 1, 0, 0.498705,-0.000528324)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130995,-0.0123686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28162,0.0056085) , 
1, 50.7868, 1, 0, 0.158769,-0.0425143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572969,-0.000457458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769875,0.0138549) , 
2, 0.97546, 1, 0, 0.61147,0.0128297) , 
10, 0.739366, 1, 0, 0.494635,-0.00145368)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33714,-0.00487678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587709,0.00494608) , 
2, 0.392638, 1, 0, 0.505215,0.0102371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772042,0.0266838) , 
3, 0.993865, 1, 0, 0.513912,0.0147007)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415601,-0.00244085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459783,-0.0216288) , 
2, 0.796164, 1, 0, 0.419727,-0.0227585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469825,-0.0051851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684767,0.0118745) , 
5, 98.8484, 1, 0, 0.614815,0.0325442) , 
2, 0.858896, 1, 0, 0.492967,-0.00199673)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636628,0.00389056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132521,-0.0120315) , 
4, 160.788, 1, 0, 0.571286,0.00972259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192744,-0.0143113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163591,-7.31677e-05) , 
6, 1.55652, 1, 0, 0.178599,-0.0419858) , 
5, 149.822, 1, 0, 0.504543,0.000934008)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277164,-0.0130035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51963,0.00028187) , 
0, 39.9262, 1, 0, 0.495745,-0.00619508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723517,0.0230529) , 
3, 0.993865, 1, 0, 0.50291,-0.00194405)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278819,-0.0193043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303362,0.00326163) , 
7, 2.54745, 1, 0, 0.28603,-0.0764486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194866,-0.0143132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541805,0.00111281) , 
2, 0.0674847, 1, 0, 0.501358,-0.00320628) , 
3, 0.0552147, 1, 0, 0.476526,-0.0116527)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316722,-0.000716385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27794,-0.0196112) , 
0, 66.5668, 1, 0, 0.304005,-0.0380333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748437,0.00854781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37551,-0.00272062) , 
5, 122.32, 1, 0, 0.564522,0.0154541) , 
5, 90.4414, 1, 0, 0.499339,0.00207109)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417612,-0.00204478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357688,-0.0330724) , 
2, 0.79517, 1, 0, 0.413238,-0.0227119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346911,-0.0177367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657545,0.00750488) , 
6, 0.609814, 1, 0, 0.637145,0.0326788) , 
2, 0.840491, 1, 0, 0.501064,-0.000985308)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0902204,-0.0205845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625576,0.00789689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443628,-0.00140263) , 
7, 2.16656, 1, 0, 0.543757,0.0180969) , 
4, 59.9059, 1, 0, 0.521003,0.0122465)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.138827,-0.0130779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671856,0.00720311) , 
4, 73.8285, 1, 0, 0.597814,0.0236654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244395,-0.0094978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733336,0.0142096) , 
10, 0.984498, 1, 0, 0.319045,-0.0313571) , 
6, 1.76341, 1, 0, 0.510251,0.00638252)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403105,6.40813e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680226,-0.0153003) , 
9, 4.91636, 1, 0, 0.44285,-0.0104534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.82048,0.00472761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.85655,0.0182519) , 
7, 1.89475, 1, 0, 0.83458,0.0435275) , 
10, 0.987671, 1, 0, 0.504971,-0.00189306)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0623452,-0.0281303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234696,0.00357441) , 
4, 114.026, 1, 0, 0.14502,-0.0608121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486402,0.000220508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881718,0.0151694) , 
10, 0.987727, 1, 0, 0.555417,0.0104243) , 
5, 62.6748, 1, 0, 0.520883,0.00442993)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412868,-0.00258868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299592,-0.0212085) , 
0, 72.5736, 1, 0, 0.387294,-0.0363542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36812,-0.00653145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621559,0.00562698) , 
2, 0.349693, 1, 0, 0.540063,0.00903208) , 
4, 104.782, 1, 0, 0.4924,-0.00512816)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108048,0.0014654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0792607,-0.0202621) , 
9, 1.18725, 1, 0, 0.0894307,-0.056295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487516,-0.00370247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618128,0.00660353) , 
4, 108.484, 1, 0, 0.571546,0.0143119) , 
8, 163.215, 1, 0, 0.502079,0.00413829)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332699,0.00397116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240423,-0.0138703) , 
0, 47.0533, 1, 0, 0.267253,-0.0461851) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.170021,-0.00735033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656366,0.0046426) , 
10, 0.684243, 1, 0, 0.552839,0.011168) , 
4, 92.1974, 1, 0, 0.498762,0.00030791)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411884,-0.00334765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714904,0.0075832) , 
5, 97.4056, 1, 0, 0.599125,0.0171891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146197,-0.00033396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249114,-0.0191494) , 
9, 3.87994, 1, 0, 0.180824,-0.0469585) , 
5, 144.887, 1, 0, 0.514367,0.00419119)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265595,-0.00392866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479871,-0.0217326) , 
10, 0.95654, 1, 0, 0.33318,-0.054995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105352,-0.0169361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57224,0.0027006) , 
4, 63.2933, 1, 0, 0.548436,0.00882641) , 
1, 28.865, 1, 0, 0.514302,-0.00129384)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0824649,-0.00707525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184586,-0.024578) , 
10, 0.910993, 1, 0, 0.12289,-0.0834944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656475,0.00478324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34856,-0.00600817) , 
5, 125.002, 1, 0, 0.547204,0.00449906) , 
5, 62.1826, 1, 0, 0.506185,-0.00400742)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335658,-0.00317712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191928,-0.0317859) , 
5, 117.145, 1, 0, 0.296414,-0.0580523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0963679,-0.0110487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613511,0.00370347) , 
8, 168.376, 1, 0, 0.536179,0.00988201) , 
0, 39.9047, 1, 0, 0.512943,0.00329836)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23123,-0.00459439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339077,-0.0207306) , 
10, 0.858735, 1, 0, 0.240635,-0.0342369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612728,-0.00184644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754709,0.00870201) , 
2, 0.871166, 1, 0, 0.665652,0.0100109) , 
10, 0.880395, 1, 0, 0.492404,-0.00802563)    );
   return;
};
 
// Clean up
inline void ReadBDT_175_325_2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_175_325_2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
