#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MC_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt


#2016 NON RESONANT SAMPLES
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/GluGluToHHTo4B_node_SM_13TeV-madgraph.txt                  
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_2_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/GluGluToHHTo4B_node_SM_13TeV-madgraph_2.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph.txt
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local.txt         
get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph_PUweights.txt  --input inputFiles/2016NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph.txt              
##2017 NONRESONANT SAMPLES
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg_PUweights.root --input inputFiles/2017NonResonantDiHiggs4BDataSets/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root    --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root    --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8_PUweights.root     --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root     --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_PUweights.root             --input inputFiles/2017NonResonantDiHiggs4BDataSets/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_PUweights.root          --input inputFiles/2017NonResonantDiHiggs4BDataSets/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_PUweights.root           --input inputFiles/2017NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local_PUweights.root     --input inputFiles/2017NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph_PUweights.root           --input inputFiles/2017NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph.txt
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8.txt
##2018 NONRESONANT SAMPLES
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8.root --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8.root --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8.root  --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT300to500_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT300to500_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8.root  --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.root             --input inputFiles/2018NonResonantDiHiggs4BDataSets/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.root          --input inputFiles/2018NonResonantDiHiggs4BDataSets/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.root      --input inputFiles/2018NonResonantDiHiggs4BDataSets/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt
get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/ZZTo4bQ01j_5f_amcatNLO_FXFX_pythia8.rooot               --input inputFiles/2018NonResonantDiHiggs4BDataSets/ZZTo4bQ01j_5f_amcatNLO_FXFX_pythia8.txt