# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/BTagCSV_Data_FileList_80x_reprocess.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --is-data --njobs=200
python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/SingleMuon_Data.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B_triggerStudies.cfg --is-data --njobs=200
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/BTagCSV_Data_FileList_80x_reprocess.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B_antiTag.cfg --is-data --njobs=300
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3




# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/Data_BTagCSV.txt  --tag=$1  --cfg=config/skim_DanielAnalysis.cfg --is-data --njobs=200
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60




