TAG="ntuples_11Dic2019_v7"
OUTDIR="root://cmseos.fnal.gov//store/user/{0}/bbbb_ntuples_CMSDAS/"

python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt              --xs 0.01053 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10

python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016_ALL.txt  --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200

### do not do single periods, just a common one
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016B_ver1.txt  --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016B_ver2.txt  --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016C.txt       --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016D.txt       --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016E.txt       --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016F.txt       --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016G.txt       --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200
### python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/data_BTagCSV_Run2016H.txt       --is-data --cfg config/skim_CMSDAS_2016DatMC.cfg --njobs 200

## NB :I dont have weights for QCD 100-200 but should all be the same
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt      --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 28060000 --puWeight=weights/2016/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root    --njobs 200
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt      --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 1710000  --puWeight=weights/2016/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root    --njobs 200
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt      --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 347500   --puWeight=weights/2016/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root    --njobs 200
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt      --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 32060    --puWeight=weights/2016/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root    --njobs 200
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt     --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 6829     --puWeight=weights/2016/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root   --njobs 200
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt    --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 1207     --puWeight=weights/2016/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root  --njobs 200
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt    --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 120      --puWeight=weights/2016/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root  --njobs 200
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt     --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs 25.25    --puWeight=weights/2016/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.root   --njobs 200

python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag=$TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt                     --cfg  config/skim_CMSDAS_2016DatMC.cfg --xs=831.76   --puWeight=weights/2016/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_PUweights.root                   --njobs 200


### the resonant signals - all normalised to 1 pb
### also here I don't have PU weights so using the signal ones (should all be identical)
### note that sample 550 is invalid
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m260.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m270.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m300.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m350.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m400.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m450.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m500.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
## python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m550.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m600.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m650.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m800.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --input inputFiles/CMSDAS/Samples2016/gg_Xradion_HH_bbbb_m900.txt --xs 1 --is-signal --cfg config/skim_CMSDAS_2016DatMC.cfg --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root --njobs 10

### klambda reweighting skims
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -20  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m20 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 1.5002657514  --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -19  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m19 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 1.36987209801 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -18  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m18 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 1.24542383004 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -17  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m17 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 1.12692094749 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -16  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m16 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 1.01436345036 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -15  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m15 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.90775133865 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -14  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m14 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.80708461236 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -13  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m13 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.71236327149 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -12  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m12 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.62358731604 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -11  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m11 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.54075674601 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -10  --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m10 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.4638715614  --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -9   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m9  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.39293176221 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -8   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m8  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.32793734844 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -7   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m7  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.26888832009 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -6   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m6  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.21578467716 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -5   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m5  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.16862641965 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -4   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m4  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.12741354756 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -3   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m3  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.09214606089 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -2   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m2  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.06282395964 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew -1   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_m1  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.03944724381 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 0    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p0  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.0220159134  --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 1    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p1  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.01052996841 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 2    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p2  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.00498940884 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 3    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p3  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.00539423469 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 4    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p4  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.01174444596 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 5    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p5  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.02404004265 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 6    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p6  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.04228102476 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 7    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p7  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.06646739229 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 8    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p8  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.09659914524 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 9    --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p9  --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.13267628361 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 10   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p10 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.1746988074  --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 11   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p11 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.22266671661 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 12   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p12 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.27658001124 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 13   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p13 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.33643869129 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 14   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p14 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.40224275676 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 15   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p15 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.47399220765 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 16   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p16 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.55168704396 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 17   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p17 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.63532726569 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 18   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p18 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.72491287284 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 19   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p19 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.82044386541 --njobs 10
python scripts/submitSkimOnTier3.py --outputDir ${OUTDIR} --tag $TAG --no-tar --no-xrdcp-tar --kl-rew 20   --kl-map weights/gg_HH_4B_SM_2016.root --input inputFiles/CMSDAS/Samples2016/gg_HH_bbbb_SM.txt --outputName GGHH4B_rew_kl_p20 --puWeight weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.root  --cfg config/skim_CMSDAS_2016DatMC.cfg --is-signal  --xs 0.9219202434  --njobs 10



